#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>

#include "iclforge/base/crc16.hpp"

namespace iclforge::ac3 {

// CRC-16 as used by AC-3 (A/52 §7.10.1): iclforge::base::crc16 (iclforge/base/crc16.hpp),
// generator polynomial x^16 + x^15 + x^2 + 1 (0x8005), MSB-first bit order, initial register 0,
// no reflection, no final XOR.
//
// A/52 defines two CRC words per syncframe: crc1 covers the first 5/8 of the
// frame and crc2 the remainder; each is chosen so that running the covered
// region (sync word excluded for crc1's region start) through this register
// yields zero. The frame-level insertion logic lives with the framer; this
// header is the register and the solver for crc1 below.
using base::crc16;

// GF(2) polynomial arithmetic modulo the generator — needed to SOLVE for
// crc1. Unlike crc2 (a plain trailing CRC), crc1 PRECEDES the region it
// protects: A/52 §7.10.1 requires the zero-initialized register to read zero
// after the first 5/8 of the syncframe (sync word excluded) is shifted
// through, and explicitly notes crc1 "is not the value generated by
// calculating the CRC of the first 5/8". Because the register is linear over
// GF(2), the requirement
//     crc1(x) * x^(8*Lbody+16) + CRC(body) == 0   (mod generator)
// solves to  crc1 = CRC(body) * inverse(x)^(8*Lbody+16),
// where body is the covered bytes AFTER the crc1 word.
namespace gf2 {

inline constexpr std::uint32_t kGenerator = 0x18005;  // x^16 + x^15 + x^2 + 1

// Product of two field elements modulo the generator (Horner over b's bits).
[[nodiscard]] constexpr std::uint16_t mul_mod(std::uint16_t a, std::uint16_t b) {
    std::uint32_t acc = 0;
    for (int bit = 15; bit >= 0; --bit) {
        acc <<= 1;
        if ((acc & 0x10000) != 0) {
            acc ^= kGenerator;
        }
        if (((b >> bit) & 1) != 0) {
            acc ^= a;
        }
    }
    return static_cast<std::uint16_t>(acc);
}

[[nodiscard]] constexpr std::uint16_t pow_mod(std::uint16_t base, std::uint64_t exponent) {
    std::uint16_t result = 1;
    while (exponent != 0) {
        if ((exponent & 1) != 0) {
            result = mul_mod(result, base);
        }
        base = mul_mod(base, base);
        exponent >>= 1;
    }
    return result;
}

// inverse(x): the generator has a +1 term, so x * ((generator XOR 1)/x) == 1
// — polynomial addition over GF(2) is XOR, not integer addition.
inline constexpr std::uint16_t kInverseX = (kGenerator ^ 1) >> 1;  // 0xC002
static_assert(mul_mod(2, kInverseX) == 1);

}  // namespace gf2

// The crc1 word for a region laid out as [crc1 (2 bytes) | body]: the value
// that drives the CRC register to zero after the whole region is processed.
[[nodiscard]] constexpr std::uint16_t solve_leading_crc(std::span<const std::byte> body) {
    const auto inverse = gf2::pow_mod(gf2::kInverseX, 8 * body.size() + 16);
    return gf2::mul_mod(crc16(body), inverse);
}

}  // namespace iclforge::ac3
