#pragma once

#include <array>

// ETSI TS 103 190-1 V1.4.1 Annex C.11, RANDOM_NOISE_TABLE. GENERATED by
// tools/generators/gen_ac4_tables.py from the attachment ts_103190_tables.c;
// do not edit by hand.

namespace iclforge::ac4::detail::tables {

// What GetRandomNoiseValue() (Pseudocode 57) looks up, in the float32 the
// attachment declares: the speech spectral frontend's noise, and the audio
// spectral frontend's noise fill (clause 5.1.4.2).
extern const std::array<float, 256> kRandomNoiseTable;

}  // namespace iclforge::ac4::detail::tables
