#include "core/tables/sfb_tables.hpp"

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>

// GENERATED by tools/generators/gen_ac4_tables.py from ETSI TS 103 190-1 V1.4.1
// Annex B's text; do not edit by hand.

namespace iclforge::ac4::detail::tables {

namespace {

struct TransformLength {
    int transform_length;
    int num_sfb;                             // Table B.1, B.2 or B.3
    std::span<const std::uint16_t> offsets;  // num_sfb + 1 entries
};

// Table B.4, the 2 048@48 column: sfb_offset for sfb 0 to 63.
constexpr std::array<std::uint16_t, 64> kSfbOffset2048 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 52, 60, 68, 76, 84, 92, 100, 108,                   // sfb 10 to 19
    116, 124, 136, 148, 160, 172, 188, 204, 220, 240,           // sfb 20 to 29
    260, 284, 308, 336, 364, 396, 432, 468, 508, 552,           // sfb 30 to 39
    600, 652, 704, 768, 832, 896, 960, 1024, 1088, 1152,        // sfb 40 to 49
    1216, 1280, 1344, 1408, 1472, 1536, 1600, 1664, 1728, 1792, // sfb 50 to 59
    1856, 1920, 1984, 2048,                                     // sfb 60 to 63
}};

// Table B.4, the 1 920@48 column: sfb_offset for sfb 0 to 61.
constexpr std::array<std::uint16_t, 62> kSfbOffset1920 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 52, 60, 68, 76, 84, 92, 100, 108,                   // sfb 10 to 19
    116, 124, 136, 148, 160, 172, 188, 204, 220, 240,           // sfb 20 to 29
    260, 284, 308, 336, 364, 396, 432, 468, 508, 552,           // sfb 30 to 39
    600, 652, 704, 768, 832, 896, 960, 1024, 1088, 1152,        // sfb 40 to 49
    1216, 1280, 1344, 1408, 1472, 1536, 1600, 1664, 1728, 1792, // sfb 50 to 59
    1856, 1920,                                                 // sfb 60 to 61
}};

// Table B.4, the 1 536@48 column: sfb_offset for sfb 0 to 55.
constexpr std::array<std::uint16_t, 56> kSfbOffset1536 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 52, 60, 68, 76, 84, 92, 100, 108,                   // sfb 10 to 19
    116, 124, 136, 148, 160, 172, 188, 204, 220, 240,           // sfb 20 to 29
    260, 284, 308, 336, 364, 396, 432, 468, 508, 552,           // sfb 30 to 39
    600, 652, 704, 768, 832, 896, 960, 1024, 1088, 1152,        // sfb 40 to 49
    1216, 1280, 1344, 1408, 1472, 1536,                         // sfb 50 to 55
}};

// Table B.5, the 1 024@48 column: sfb_offset for sfb 0 to 49.
constexpr std::array<std::uint16_t, 50> kSfbOffset1024 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 48, 56, 64, 72, 80, 88, 96, 108, 120,                   // sfb 10 to 19
    132, 144, 160, 176, 196, 216, 240, 264, 292, 320,           // sfb 20 to 29
    352, 384, 416, 448, 480, 512, 544, 576, 608, 640,           // sfb 30 to 39
    672, 704, 736, 768, 800, 832, 864, 896, 928, 1024,          // sfb 40 to 49
}};

// Table B.5, the 960@48 column: sfb_offset for sfb 0 to 49.
constexpr std::array<std::uint16_t, 50> kSfbOffset960 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 48, 56, 64, 72, 80, 88, 96, 108, 120,                   // sfb 10 to 19
    132, 144, 160, 176, 196, 216, 240, 264, 292, 320,           // sfb 20 to 29
    352, 384, 416, 448, 480, 512, 544, 576, 608, 640,           // sfb 30 to 39
    672, 704, 736, 768, 800, 832, 864, 896, 928, 960,           // sfb 40 to 49
}};

// Table B.5, the 768@48 column: sfb_offset for sfb 0 to 43.
constexpr std::array<std::uint16_t, 44> kSfbOffset768 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 48, 56, 64, 72, 80, 88, 96, 108, 120,                   // sfb 10 to 19
    132, 144, 160, 176, 196, 216, 240, 264, 292, 320,           // sfb 20 to 29
    352, 384, 416, 448, 480, 512, 544, 576, 608, 640,           // sfb 30 to 39
    672, 704, 736, 768,                                         // sfb 40 to 43
}};

// Table B.6, the 512@48 column: sfb_offset for sfb 0 to 36.
constexpr std::array<std::uint16_t, 37> kSfbOffset512 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 48, 52, 56, 60, 68, 76, 84, 92,                     // sfb 10 to 19
    100, 112, 124, 136, 148, 164, 184, 208, 236, 268,           // sfb 20 to 29
    300, 332, 364, 396, 428, 460, 512,                          // sfb 30 to 36
}};

// Table B.6, the 480@48 column: sfb_offset for sfb 0 to 36.
constexpr std::array<std::uint16_t, 37> kSfbOffset480 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 48, 52, 56, 60, 68, 76, 84, 92,                     // sfb 10 to 19
    100, 112, 124, 136, 148, 164, 184, 208, 236, 268,           // sfb 20 to 29
    300, 332, 364, 396, 428, 460, 480,                          // sfb 30 to 36
}};

// Table B.6, the 384@48 column: sfb_offset for sfb 0 to 33.
constexpr std::array<std::uint16_t, 34> kSfbOffset384 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 48, 52, 56, 60, 68, 76, 84, 92,                     // sfb 10 to 19
    100, 112, 124, 136, 148, 164, 184, 208, 236, 268,           // sfb 20 to 29
    300, 332, 364, 384,                                         // sfb 30 to 33
}};

// Table B.7, the 256@48 column: sfb_offset for sfb 0 to 20.
constexpr std::array<std::uint16_t, 21> kSfbOffset256 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 36, 44,                        // sfb 0 to 9
    52, 64, 76, 92, 108, 128, 148, 172, 196, 224,               // sfb 10 to 19
    256,                                                        // sfb 20
}};

// Table B.7, the 240@48 column: sfb_offset for sfb 0 to 20.
constexpr std::array<std::uint16_t, 21> kSfbOffset240 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 36, 44,                        // sfb 0 to 9
    52, 64, 76, 92, 108, 128, 148, 172, 196, 224,               // sfb 10 to 19
    240,                                                        // sfb 20
}};

// Table B.7, the 192@48 column: sfb_offset for sfb 0 to 18.
constexpr std::array<std::uint16_t, 19> kSfbOffset192 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 36, 44,                        // sfb 0 to 9
    52, 64, 76, 92, 108, 128, 148, 172, 192,                    // sfb 10 to 18
}};

// Table B.7, the 128@48 column: sfb_offset for sfb 0 to 14.
constexpr std::array<std::uint16_t, 15> kSfbOffset128 = {{
    0, 4, 8, 12, 16, 20, 28, 36, 44, 56,                        // sfb 0 to 9
    68, 80, 96, 112, 128,                                       // sfb 10 to 14
}};

// Table B.7, the 120@48 column: sfb_offset for sfb 0 to 14.
constexpr std::array<std::uint16_t, 15> kSfbOffset120 = {{
    0, 4, 8, 12, 16, 20, 28, 36, 44, 56,                        // sfb 0 to 9
    68, 80, 96, 112, 120,                                       // sfb 10 to 14
}};

// Table B.7, the 96@48 column: sfb_offset for sfb 0 to 12.
constexpr std::array<std::uint16_t, 13> kSfbOffset96 = {{
    0, 4, 8, 12, 16, 20, 28, 36, 44, 56,                        // sfb 0 to 9
    68, 80, 96,                                                 // sfb 10 to 12
}};

constexpr std::array<TransformLength, 15> kTransformLengths = {{
    {2048, 63, kSfbOffset2048},
    {1920, 61, kSfbOffset1920},
    {1536, 55, kSfbOffset1536},
    {1024, 49, kSfbOffset1024},
    {960, 49, kSfbOffset960},
    {768, 43, kSfbOffset768},
    {512, 36, kSfbOffset512},
    {480, 36, kSfbOffset480},
    {384, 33, kSfbOffset384},
    {256, 20, kSfbOffset256},
    {240, 20, kSfbOffset240},
    {192, 18, kSfbOffset192},
    {128, 14, kSfbOffset128},
    {120, 14, kSfbOffset120},
    {96, 12, kSfbOffset96},
}};

// Table B.4, the 4 096@96 column: sfb_offset for sfb 0 to 79.
constexpr std::array<std::uint16_t, 80> kSfbOffset964096 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 52, 60, 68, 76, 84, 92, 100, 108,                   // sfb 10 to 19
    116, 124, 136, 148, 160, 172, 188, 204, 220, 240,           // sfb 20 to 29
    260, 284, 308, 336, 364, 396, 432, 468, 508, 552,           // sfb 30 to 39
    600, 652, 704, 768, 832, 896, 960, 1024, 1088, 1152,        // sfb 40 to 49
    1216, 1280, 1344, 1408, 1472, 1536, 1600, 1664, 1728, 1792, // sfb 50 to 59
    1856, 1920, 1984, 2048, 2176, 2304, 2432, 2560, 2688, 2816, // sfb 60 to 69
    2944, 3072, 3200, 3328, 3456, 3584, 3712, 3840, 3968, 4096, // sfb 70 to 79
}};

// Table B.4, the 3 840@96 column: sfb_offset for sfb 0 to 76.
constexpr std::array<std::uint16_t, 77> kSfbOffset963840 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 52, 60, 68, 76, 84, 92, 100, 108,                   // sfb 10 to 19
    116, 124, 136, 148, 160, 172, 188, 204, 220, 240,           // sfb 20 to 29
    260, 284, 308, 336, 364, 396, 432, 468, 508, 552,           // sfb 30 to 39
    600, 652, 704, 768, 832, 896, 960, 1024, 1088, 1152,        // sfb 40 to 49
    1216, 1280, 1344, 1408, 1472, 1536, 1600, 1664, 1728, 1792, // sfb 50 to 59
    1856, 1920, 2048, 2176, 2304, 2432, 2560, 2688, 2816, 2944, // sfb 60 to 69
    3072, 3200, 3328, 3456, 3584, 3712, 3840,                   // sfb 70 to 76
}};

// Table B.4, the 3 072@96 column: sfb_offset for sfb 0 to 67.
constexpr std::array<std::uint16_t, 68> kSfbOffset963072 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 52, 60, 68, 76, 84, 92, 100, 108,                   // sfb 10 to 19
    116, 124, 136, 148, 160, 172, 188, 204, 220, 240,           // sfb 20 to 29
    260, 284, 308, 336, 364, 396, 432, 468, 508, 552,           // sfb 30 to 39
    600, 652, 704, 768, 832, 896, 960, 1024, 1088, 1152,        // sfb 40 to 49
    1216, 1280, 1344, 1408, 1472, 1536, 1664, 1792, 1920, 2048, // sfb 50 to 59
    2176, 2304, 2432, 2560, 2688, 2816, 2944, 3072,             // sfb 60 to 67
}};

// Table B.5, the 2 048@96 column: sfb_offset for sfb 0 to 57.
constexpr std::array<std::uint16_t, 58> kSfbOffset962048 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 48, 56, 64, 72, 80, 88, 96, 108, 120,                   // sfb 10 to 19
    132, 144, 160, 176, 196, 216, 240, 264, 292, 320,           // sfb 20 to 29
    352, 384, 416, 448, 480, 512, 544, 576, 608, 640,           // sfb 30 to 39
    672, 704, 736, 768, 800, 832, 864, 896, 928, 1024,          // sfb 40 to 49
    1152, 1280, 1408, 1536, 1664, 1792, 1920, 2048,             // sfb 50 to 57
}};

// Table B.5, the 1 920@96 column: sfb_offset for sfb 0 to 57.
constexpr std::array<std::uint16_t, 58> kSfbOffset961920 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 48, 56, 64, 72, 80, 88, 96, 108, 120,                   // sfb 10 to 19
    132, 144, 160, 176, 196, 216, 240, 264, 292, 320,           // sfb 20 to 29
    352, 384, 416, 448, 480, 512, 544, 576, 608, 640,           // sfb 30 to 39
    672, 704, 736, 768, 800, 832, 864, 896, 928, 960,           // sfb 40 to 49
    1024, 1152, 1280, 1408, 1536, 1664, 1792, 1920,             // sfb 50 to 57
}};

// Table B.5, the 1 536@96 column: sfb_offset for sfb 0 to 49.
constexpr std::array<std::uint16_t, 50> kSfbOffset961536 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 48, 56, 64, 72, 80, 88, 96, 108, 120,                   // sfb 10 to 19
    132, 144, 160, 176, 196, 216, 240, 264, 292, 320,           // sfb 20 to 29
    352, 384, 416, 448, 480, 512, 544, 576, 608, 640,           // sfb 30 to 39
    672, 704, 736, 768, 896, 1024, 1152, 1280, 1408, 1536,      // sfb 40 to 49
}};

// Table B.6, the 1 024@96 column: sfb_offset for sfb 0 to 44.
constexpr std::array<std::uint16_t, 45> kSfbOffset961024 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 48, 52, 56, 60, 68, 76, 84, 92,                     // sfb 10 to 19
    100, 112, 124, 136, 148, 164, 184, 208, 236, 268,           // sfb 20 to 29
    300, 332, 364, 396, 428, 460, 512, 576, 640, 704,           // sfb 30 to 39
    768, 832, 896, 960, 1024,                                   // sfb 40 to 44
}};

// Table B.6, the 960@96 column: sfb_offset for sfb 0 to 44.
constexpr std::array<std::uint16_t, 45> kSfbOffset96960 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 48, 52, 56, 60, 68, 76, 84, 92,                     // sfb 10 to 19
    100, 112, 124, 136, 148, 164, 184, 208, 236, 268,           // sfb 20 to 29
    300, 332, 364, 396, 428, 460, 480, 512, 576, 640,           // sfb 30 to 39
    704, 768, 832, 896, 960,                                    // sfb 40 to 44
}};

// Table B.6, the 768@96 column: sfb_offset for sfb 0 to 39.
constexpr std::array<std::uint16_t, 40> kSfbOffset96768 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 48, 52, 56, 60, 68, 76, 84, 92,                     // sfb 10 to 19
    100, 112, 124, 136, 148, 164, 184, 208, 236, 268,           // sfb 20 to 29
    300, 332, 364, 384, 448, 512, 576, 640, 704, 768,           // sfb 30 to 39
}};

// Table B.7, the 512@96 column: sfb_offset for sfb 0 to 28.
constexpr std::array<std::uint16_t, 29> kSfbOffset96512 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 36, 44,                        // sfb 0 to 9
    52, 64, 76, 92, 108, 128, 148, 172, 196, 224,               // sfb 10 to 19
    256, 288, 320, 352, 384, 416, 448, 480, 512,                // sfb 20 to 28
}};

// Table B.7, the 480@96 column: sfb_offset for sfb 0 to 28.
constexpr std::array<std::uint16_t, 29> kSfbOffset96480 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 36, 44,                        // sfb 0 to 9
    52, 64, 76, 92, 108, 128, 148, 172, 196, 224,               // sfb 10 to 19
    240, 256, 288, 320, 352, 384, 416, 448, 480,                // sfb 20 to 28
}};

// Table B.7, the 384@96 column: sfb_offset for sfb 0 to 24.
constexpr std::array<std::uint16_t, 25> kSfbOffset96384 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 36, 44,                        // sfb 0 to 9
    52, 64, 76, 92, 108, 128, 148, 172, 192, 224,               // sfb 10 to 19
    256, 288, 320, 352, 384,                                    // sfb 20 to 24
}};

// Table B.7, the 256@96 column: sfb_offset for sfb 0 to 22.
constexpr std::array<std::uint16_t, 23> kSfbOffset96256 = {{
    0, 4, 8, 12, 16, 20, 28, 36, 44, 56,                        // sfb 0 to 9
    68, 80, 96, 112, 128, 144, 160, 176, 192, 208,              // sfb 10 to 19
    224, 240, 256,                                              // sfb 20 to 22
}};

// Table B.7, the 240@96 column: sfb_offset for sfb 0 to 22.
constexpr std::array<std::uint16_t, 23> kSfbOffset96240 = {{
    0, 4, 8, 12, 16, 20, 28, 36, 44, 56,                        // sfb 0 to 9
    68, 80, 96, 112, 120, 128, 144, 160, 176, 192,              // sfb 10 to 19
    208, 224, 240,                                              // sfb 20 to 22
}};

// Table B.7, the 192@96 column: sfb_offset for sfb 0 to 18.
constexpr std::array<std::uint16_t, 19> kSfbOffset96192 = {{
    0, 4, 8, 12, 16, 20, 28, 36, 44, 56,                        // sfb 0 to 9
    68, 80, 96, 112, 128, 144, 160, 176, 192,                   // sfb 10 to 18
}};

constexpr std::array<TransformLength, 15> kTransformLengths96 = {{
    {4096, 79, kSfbOffset964096},
    {3840, 76, kSfbOffset963840},
    {3072, 67, kSfbOffset963072},
    {2048, 57, kSfbOffset962048},
    {1920, 57, kSfbOffset961920},
    {1536, 49, kSfbOffset961536},
    {1024, 44, kSfbOffset961024},
    {960, 44, kSfbOffset96960},
    {768, 39, kSfbOffset96768},
    {512, 28, kSfbOffset96512},
    {480, 28, kSfbOffset96480},
    {384, 24, kSfbOffset96384},
    {256, 22, kSfbOffset96256},
    {240, 22, kSfbOffset96240},
    {192, 18, kSfbOffset96192},
}};

// Table B.4, the 8 192@192 column: sfb_offset for sfb 0 to 111.
constexpr std::array<std::uint16_t, 112> kSfbOffset1928192 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 52, 60, 68, 76, 84, 92, 100, 108,                   // sfb 10 to 19
    116, 124, 136, 148, 160, 172, 188, 204, 220, 240,           // sfb 20 to 29
    260, 284, 308, 336, 364, 396, 432, 468, 508, 552,           // sfb 30 to 39
    600, 652, 704, 768, 832, 896, 960, 1024, 1088, 1152,        // sfb 40 to 49
    1216, 1280, 1344, 1408, 1472, 1536, 1600, 1664, 1728, 1792, // sfb 50 to 59
    1856, 1920, 1984, 2048, 2176, 2304, 2432, 2560, 2688, 2816, // sfb 60 to 69
    2944, 3072, 3200, 3328, 3456, 3584, 3712, 3840, 3968, 4096, // sfb 70 to 79
    4224, 4352, 4480, 4608, 4736, 4864, 4992, 5120, 5248, 5376, // sfb 80 to 89
    5504, 5632, 5760, 5888, 6016, 6144, 6272, 6400, 6528, 6656, // sfb 90 to 99
    6784, 6912, 7040, 7168, 7296, 7424, 7552, 7680, 7808, 7936, // sfb 100 to 109
    8064, 8192,                                                 // sfb 110 to 111
}};

// Table B.4, the 7 680@192 column: sfb_offset for sfb 0 to 106.
constexpr std::array<std::uint16_t, 107> kSfbOffset1927680 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 52, 60, 68, 76, 84, 92, 100, 108,                   // sfb 10 to 19
    116, 124, 136, 148, 160, 172, 188, 204, 220, 240,           // sfb 20 to 29
    260, 284, 308, 336, 364, 396, 432, 468, 508, 552,           // sfb 30 to 39
    600, 652, 704, 768, 832, 896, 960, 1024, 1088, 1152,        // sfb 40 to 49
    1216, 1280, 1344, 1408, 1472, 1536, 1600, 1664, 1728, 1792, // sfb 50 to 59
    1856, 1920, 2048, 2176, 2304, 2432, 2560, 2688, 2816, 2944, // sfb 60 to 69
    3072, 3200, 3328, 3456, 3584, 3712, 3840, 3968, 4096, 4224, // sfb 70 to 79
    4352, 4480, 4608, 4736, 4864, 4992, 5120, 5248, 5376, 5504, // sfb 80 to 89
    5632, 5760, 5888, 6016, 6144, 6272, 6400, 6528, 6656, 6784, // sfb 90 to 99
    6912, 7040, 7168, 7296, 7424, 7552, 7680,                   // sfb 100 to 106
}};

// Table B.4, the 6 144@192 column: sfb_offset for sfb 0 to 91.
constexpr std::array<std::uint16_t, 92> kSfbOffset1926144 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 52, 60, 68, 76, 84, 92, 100, 108,                   // sfb 10 to 19
    116, 124, 136, 148, 160, 172, 188, 204, 220, 240,           // sfb 20 to 29
    260, 284, 308, 336, 364, 396, 432, 468, 508, 552,           // sfb 30 to 39
    600, 652, 704, 768, 832, 896, 960, 1024, 1088, 1152,        // sfb 40 to 49
    1216, 1280, 1344, 1408, 1472, 1536, 1664, 1792, 1920, 2048, // sfb 50 to 59
    2176, 2304, 2432, 2560, 2688, 2816, 2944, 3072, 3200, 3328, // sfb 60 to 69
    3456, 3584, 3712, 3840, 3968, 4096, 4224, 4352, 4480, 4608, // sfb 70 to 79
    4736, 4864, 4992, 5120, 5248, 5376, 5504, 5632, 5760, 5888, // sfb 80 to 89
    6016, 6144,                                                 // sfb 90 to 91
}};

// Table B.5, the 4 096@192 column: sfb_offset for sfb 0 to 73.
constexpr std::array<std::uint16_t, 74> kSfbOffset1924096 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 48, 56, 64, 72, 80, 88, 96, 108, 120,                   // sfb 10 to 19
    132, 144, 160, 176, 196, 216, 240, 264, 292, 320,           // sfb 20 to 29
    352, 384, 416, 448, 480, 512, 544, 576, 608, 640,           // sfb 30 to 39
    672, 704, 736, 768, 800, 832, 864, 896, 928, 1024,          // sfb 40 to 49
    1152, 1280, 1408, 1536, 1664, 1792, 1920, 2048, 2176, 2304, // sfb 50 to 59
    2432, 2560, 2688, 2816, 2944, 3072, 3200, 3328, 3456, 3584, // sfb 60 to 69
    3712, 3840, 3968, 4096,                                     // sfb 70 to 73
}};

// Table B.5, the 3 840@192 column: sfb_offset for sfb 0 to 72.
constexpr std::array<std::uint16_t, 73> kSfbOffset1923840 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 48, 56, 64, 72, 80, 88, 96, 108, 120,                   // sfb 10 to 19
    132, 144, 160, 176, 196, 216, 240, 264, 292, 320,           // sfb 20 to 29
    352, 384, 416, 448, 480, 512, 544, 576, 608, 640,           // sfb 30 to 39
    672, 704, 736, 768, 800, 832, 864, 896, 928, 960,           // sfb 40 to 49
    1024, 1152, 1280, 1408, 1536, 1664, 1792, 1920, 2048, 2176, // sfb 50 to 59
    2304, 2432, 2560, 2688, 2816, 2944, 3072, 3200, 3328, 3456, // sfb 60 to 69
    3584, 3712, 3840,                                           // sfb 70 to 72
}};

// Table B.5, the 3 072@192 column: sfb_offset for sfb 0 to 61.
constexpr std::array<std::uint16_t, 62> kSfbOffset1923072 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 48, 56, 64, 72, 80, 88, 96, 108, 120,                   // sfb 10 to 19
    132, 144, 160, 176, 196, 216, 240, 264, 292, 320,           // sfb 20 to 29
    352, 384, 416, 448, 480, 512, 544, 576, 608, 640,           // sfb 30 to 39
    672, 704, 736, 768, 896, 1024, 1152, 1280, 1408, 1536,      // sfb 40 to 49
    1664, 1792, 1920, 2048, 2176, 2304, 2432, 2560, 2688, 2816, // sfb 50 to 59
    2944, 3072,                                                 // sfb 60 to 61
}};

// Table B.6, the 2 048@192 column: sfb_offset for sfb 0 to 60.
constexpr std::array<std::uint16_t, 61> kSfbOffset1922048 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 48, 52, 56, 60, 68, 76, 84, 92,                     // sfb 10 to 19
    100, 112, 124, 136, 148, 164, 184, 208, 236, 268,           // sfb 20 to 29
    300, 332, 364, 396, 428, 460, 512, 576, 640, 704,           // sfb 30 to 39
    768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344,     // sfb 40 to 49
    1408, 1472, 1536, 1600, 1664, 1728, 1792, 1856, 1920, 1984, // sfb 50 to 59
    2048,                                                       // sfb 60
}};

// Table B.6, the 1 920@192 column: sfb_offset for sfb 0 to 59.
constexpr std::array<std::uint16_t, 60> kSfbOffset1921920 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 48, 52, 56, 60, 68, 76, 84, 92,                     // sfb 10 to 19
    100, 112, 124, 136, 148, 164, 184, 208, 236, 268,           // sfb 20 to 29
    300, 332, 364, 396, 428, 460, 480, 512, 576, 640,           // sfb 30 to 39
    704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280,      // sfb 40 to 49
    1344, 1408, 1472, 1536, 1600, 1664, 1728, 1792, 1856, 1920, // sfb 50 to 59
}};

// Table B.6, the 1 536@192 column: sfb_offset for sfb 0 to 51.
constexpr std::array<std::uint16_t, 52> kSfbOffset1921536 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 32, 36,                        // sfb 0 to 9
    40, 44, 48, 52, 56, 60, 68, 76, 84, 92,                     // sfb 10 to 19
    100, 112, 124, 136, 148, 164, 184, 208, 236, 268,           // sfb 20 to 29
    300, 332, 364, 384, 448, 512, 576, 640, 704, 768,           // sfb 30 to 39
    832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408,    // sfb 40 to 49
    1472, 1536,                                                 // sfb 50 to 51
}};

// Table B.7, the 1 024@192 column: sfb_offset for sfb 0 to 36.
constexpr std::array<std::uint16_t, 37> kSfbOffset1921024 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 36, 44,                        // sfb 0 to 9
    52, 64, 76, 92, 108, 128, 148, 172, 196, 224,               // sfb 10 to 19
    256, 288, 320, 352, 384, 416, 448, 480, 512, 576,           // sfb 20 to 29
    640, 704, 768, 832, 896, 960, 1024,                         // sfb 30 to 36
}};

// Table B.7, the 960@192 column: sfb_offset for sfb 0 to 36.
constexpr std::array<std::uint16_t, 37> kSfbOffset192960 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 36, 44,                        // sfb 0 to 9
    52, 64, 76, 92, 108, 128, 148, 172, 196, 224,               // sfb 10 to 19
    240, 256, 288, 320, 352, 384, 416, 448, 480, 512,           // sfb 20 to 29
    576, 640, 704, 768, 832, 896, 960,                          // sfb 30 to 36
}};

// Table B.7, the 768@192 column: sfb_offset for sfb 0 to 30.
constexpr std::array<std::uint16_t, 31> kSfbOffset192768 = {{
    0, 4, 8, 12, 16, 20, 24, 28, 36, 44,                        // sfb 0 to 9
    52, 64, 76, 92, 108, 128, 148, 172, 192, 224,               // sfb 10 to 19
    256, 288, 320, 352, 384, 448, 512, 576, 640, 704,           // sfb 20 to 29
    768,                                                        // sfb 30
}};

// Table B.7, the 512@192 column: sfb_offset for sfb 0 to 30.
constexpr std::array<std::uint16_t, 31> kSfbOffset192512 = {{
    0, 4, 8, 12, 16, 20, 28, 36, 44, 56,                        // sfb 0 to 9
    68, 80, 96, 112, 128, 144, 160, 176, 192, 208,              // sfb 10 to 19
    224, 240, 256, 288, 320, 352, 384, 416, 448, 480,           // sfb 20 to 29
    512,                                                        // sfb 30
}};

// Table B.7, the 480@192 column: sfb_offset for sfb 0 to 30.
constexpr std::array<std::uint16_t, 31> kSfbOffset192480 = {{
    0, 4, 8, 12, 16, 20, 28, 36, 44, 56,                        // sfb 0 to 9
    68, 80, 96, 112, 120, 128, 144, 160, 176, 192,              // sfb 10 to 19
    208, 224, 240, 256, 288, 320, 352, 384, 416, 448,           // sfb 20 to 29
    480,                                                        // sfb 30
}};

// Table B.7, the 384@192 column: sfb_offset for sfb 0 to 24.
constexpr std::array<std::uint16_t, 25> kSfbOffset192384 = {{
    0, 4, 8, 12, 16, 20, 28, 36, 44, 56,                        // sfb 0 to 9
    68, 80, 96, 112, 128, 144, 160, 176, 192, 224,              // sfb 10 to 19
    256, 288, 320, 352, 384,                                    // sfb 20 to 24
}};

constexpr std::array<TransformLength, 15> kTransformLengths192 = {{
    {8192, 111, kSfbOffset1928192},
    {7680, 106, kSfbOffset1927680},
    {6144, 91, kSfbOffset1926144},
    {4096, 73, kSfbOffset1924096},
    {3840, 72, kSfbOffset1923840},
    {3072, 61, kSfbOffset1923072},
    {2048, 60, kSfbOffset1922048},
    {1920, 59, kSfbOffset1921920},
    {1536, 51, kSfbOffset1921536},
    {1024, 36, kSfbOffset1921024},
    {960, 36, kSfbOffset192960},
    {768, 30, kSfbOffset192768},
    {512, 30, kSfbOffset192512},
    {480, 30, kSfbOffset192480},
    {384, 24, kSfbOffset192384},
}};

// Table B.8: max_sfb_master[2 048], by row, to n_sfb_side[1 024], [512], [256], [128].
constexpr std::array<std::uint8_t, 128> kSfbSide2048 = {{
     0,  0,  0,  0,     // 0
     1,  1,  1,  1,     // 1
     1,  1,  1,  1,     // 2
     2,  1,  1,  1,     // 3
     2,  1,  1,  1,     // 4
     3,  2,  1,  1,     // 5
     3,  2,  1,  1,     // 6
     4,  2,  1,  1,     // 7
     4,  2,  1,  1,     // 8
     5,  3,  2,  1,     // 9
     5,  3,  2,  1,     // 10
     6,  3,  2,  1,     // 11
     7,  4,  2,  1,     // 12
     8,  4,  2,  1,     // 13
     9,  5,  3,  2,     // 14
    10,  5,  3,  2,     // 15
    11,  6,  3,  2,     // 16
    11,  6,  3,  2,     // 17
    12,  7,  4,  2,     // 18
    12,  7,  4,  2,     // 19
    13,  8,  4,  2,     // 20
    13,  8,  4,  2,     // 21
    14,  9,  5,  3,     // 22
    15, 10,  5,  3,     // 23
    15, 10,  5,  3,     // 24
    16, 11,  6,  3,     // 25
    17, 12,  6,  3,     // 26
    18, 13,  7,  4,     // 27
    19, 14,  7,  4,     // 28
    19, 15,  8,  4,     // 29
    20, 16,  8,  5,     // 30
    21, 17,  8,  5,     // 31
}};

// Table B.9: max_sfb_master[1 024], by row, to n_sfb_side[512], [256], [128].
constexpr std::array<std::uint8_t, 96> kSfbSide1024 = {{
     0,  0,  0,         // 0
     1,  1,  1,         // 1
     1,  1,  1,         // 2
     2,  1,  1,         // 3
     2,  1,  1,         // 4
     3,  2,  1,         // 5
     3,  2,  1,         // 6
     4,  2,  1,         // 7
     4,  2,  1,         // 8
     5,  3,  2,         // 9
     5,  3,  2,         // 10
     6,  3,  2,         // 11
     7,  4,  2,         // 12
     8,  4,  2,         // 13
     9,  5,  3,         // 14
    10,  5,  3,         // 15
    11,  6,  3,         // 16
    12,  6,  3,         // 17
    14,  7,  4,         // 18
    15,  8,  4,         // 19
    16,  8,  5,         // 20
    17,  8,  5,         // 21
    18,  9,  5,         // 22
    19,  9,  6,         // 23
    20, 10,  6,         // 24
    21, 11,  6,         // 25
    22, 11,  7,         // 26
    23, 12,  7,         // 27
    24, 12,  8,         // 28
    25, 13,  8,         // 29
    26, 13,  8,         // 30
    27, 14,  9,         // 31
}};

// Table B.10: max_sfb_master[512], by row, to n_sfb_side[256], [128].
constexpr std::array<std::uint8_t, 64> kSfbSide512 = {{
     0,  0,             // 0
     1,  1,             // 1
     1,  1,             // 2
     2,  1,             // 3
     2,  1,             // 4
     3,  2,             // 5
     3,  2,             // 6
     4,  2,             // 7
     4,  2,             // 8
     5,  3,             // 9
     5,  3,             // 10
     6,  3,             // 11
     6,  3,             // 12
     7,  4,             // 13
     7,  4,             // 14
     8,  4,             // 15
     8,  5,             // 16
     9,  5,             // 17
     9,  6,             // 18
    10,  6,             // 19
    10,  6,             // 20
    11,  6,             // 21
    11,  7,             // 22
    12,  7,             // 23
    12,  8,             // 24
    13,  8,             // 25
    13,  9,             // 26
    14,  9,             // 27
    15, 10,             // 28
    16, 10,             // 29
    17, 11,             // 30
    17, 12,             // 31
}};

// Table B.11: max_sfb_master[256], by row, to n_sfb_side[128].
constexpr std::array<std::uint8_t, 16> kSfbSide256 = {{
     0,                 // 0
     1,                 // 1
     1,                 // 2
     2,                 // 3
     2,                 // 4
     3,                 // 5
     3,                 // 6
     4,                 // 7
     5,                 // 8
     6,                 // 9
     6,                 // 10
     7,                 // 11
     8,                 // 12
     9,                 // 13
     9,                 // 14
    10,                 // 15
}};

// Table B.12: max_sfb_master[1 920], by row, to n_sfb_side[960], [480], [240], [120].
constexpr std::array<std::uint8_t, 128> kSfbSide1920 = {{
     0,  0,  0,  0,     // 0
     1,  1,  1,  1,     // 1
     1,  1,  1,  1,     // 2
     2,  1,  1,  1,     // 3
     2,  1,  1,  1,     // 4
     3,  2,  1,  1,     // 5
     3,  2,  1,  1,     // 6
     4,  2,  1,  1,     // 7
     4,  2,  1,  1,     // 8
     5,  3,  2,  1,     // 9
     5,  3,  2,  1,     // 10
     6,  3,  2,  1,     // 11
     7,  4,  2,  1,     // 12
     8,  4,  2,  1,     // 13
     9,  5,  3,  2,     // 14
    10,  5,  3,  2,     // 15
    11,  6,  3,  2,     // 16
    11,  6,  3,  2,     // 17
    12,  7,  4,  2,     // 18
    12,  7,  4,  2,     // 19
    13,  8,  4,  2,     // 20
    13,  8,  4,  2,     // 21
    14,  9,  5,  3,     // 22
    15, 10,  5,  3,     // 23
    15, 10,  5,  3,     // 24
    16, 11,  6,  3,     // 25
    17, 12,  6,  3,     // 26
    18, 13,  7,  4,     // 27
    19, 14,  7,  4,     // 28
    19, 15,  8,  4,     // 29
    20, 16,  8,  5,     // 30
    21, 17,  8,  5,     // 31
}};

// Table B.13: max_sfb_master[960], by row, to n_sfb_side[480], [240], [120].
constexpr std::array<std::uint8_t, 96> kSfbSide960 = {{
     0,  0,  0,         // 0
     1,  1,  1,         // 1
     1,  1,  1,         // 2
     2,  1,  1,         // 3
     2,  1,  1,         // 4
     3,  2,  1,         // 5
     3,  2,  1,         // 6
     4,  2,  1,         // 7
     4,  2,  1,         // 8
     5,  3,  2,         // 9
     5,  3,  2,         // 10
     6,  3,  2,         // 11
     7,  4,  2,         // 12
     8,  4,  2,         // 13
     9,  5,  3,         // 14
    10,  5,  3,         // 15
    11,  6,  3,         // 16
    12,  6,  3,         // 17
    14,  7,  4,         // 18
    15,  8,  4,         // 19
    16,  8,  5,         // 20
    17,  8,  5,         // 21
    18,  9,  5,         // 22
    19,  9,  6,         // 23
    20, 10,  6,         // 24
    21, 11,  6,         // 25
    22, 11,  7,         // 26
    23, 12,  7,         // 27
    24, 12,  8,         // 28
    25, 13,  8,         // 29
    26, 13,  8,         // 30
    27, 14,  9,         // 31
}};

// Table B.14: max_sfb_master[480], by row, to n_sfb_side[240], [120].
constexpr std::array<std::uint8_t, 64> kSfbSide480 = {{
     0,  0,             // 0
     1,  1,             // 1
     1,  1,             // 2
     2,  1,             // 3
     2,  1,             // 4
     3,  2,             // 5
     3,  2,             // 6
     4,  2,             // 7
     4,  2,             // 8
     5,  3,             // 9
     5,  3,             // 10
     6,  3,             // 11
     6,  3,             // 12
     7,  4,             // 13
     7,  4,             // 14
     8,  4,             // 15
     8,  5,             // 16
     9,  5,             // 17
     9,  6,             // 18
    10,  6,             // 19
    10,  6,             // 20
    11,  6,             // 21
    11,  7,             // 22
    12,  7,             // 23
    12,  8,             // 24
    13,  8,             // 25
    13,  9,             // 26
    14,  9,             // 27
    15, 10,             // 28
    16, 10,             // 29
    17, 11,             // 30
    17, 12,             // 31
}};

// Table B.15: max_sfb_master[240], by row, to n_sfb_side[120].
constexpr std::array<std::uint8_t, 16> kSfbSide240 = {{
     0,                 // 0
     1,                 // 1
     1,                 // 2
     2,                 // 3
     2,                 // 4
     3,                 // 5
     3,                 // 6
     4,                 // 7
     5,                 // 8
     6,                 // 9
     6,                 // 10
     7,                 // 11
     8,                 // 12
     9,                 // 13
     9,                 // 14
    10,                 // 15
}};

// Table B.16: max_sfb_master[1 536], by row, to n_sfb_side[768], [384], [192], [96].
constexpr std::array<std::uint8_t, 128> kSfbSide1536 = {{
     0,  0,  0,  0,     // 0
     1,  1,  1,  1,     // 1
     1,  1,  1,  1,     // 2
     2,  1,  1,  1,     // 3
     2,  1,  1,  1,     // 4
     3,  2,  1,  1,     // 5
     3,  2,  1,  1,     // 6
     4,  2,  1,  1,     // 7
     4,  2,  1,  1,     // 8
     5,  3,  2,  1,     // 9
     5,  3,  2,  1,     // 10
     6,  3,  2,  1,     // 11
     7,  4,  2,  1,     // 12
     8,  4,  2,  1,     // 13
     9,  5,  3,  2,     // 14
    10,  5,  3,  2,     // 15
    11,  6,  3,  2,     // 16
    11,  6,  3,  2,     // 17
    12,  7,  4,  2,     // 18
    12,  7,  4,  2,     // 19
    13,  8,  4,  2,     // 20
    13,  8,  4,  2,     // 21
    14,  9,  5,  3,     // 22
    15, 10,  5,  3,     // 23
    15, 10,  5,  3,     // 24
    16, 11,  6,  3,     // 25
    17, 12,  6,  3,     // 26
    18, 13,  7,  4,     // 27
    19, 14,  7,  4,     // 28
    19, 15,  8,  4,     // 29
    20, 16,  8,  5,     // 30
    21, 17,  8,  5,     // 31
}};

// Table B.17: max_sfb_master[768], by row, to n_sfb_side[384], [192], [96].
constexpr std::array<std::uint8_t, 96> kSfbSide768 = {{
     0,  0,  0,         // 0
     1,  1,  1,         // 1
     1,  1,  1,         // 2
     2,  1,  1,         // 3
     2,  1,  1,         // 4
     3,  2,  1,         // 5
     3,  2,  1,         // 6
     4,  2,  1,         // 7
     4,  2,  1,         // 8
     5,  3,  2,         // 9
     5,  3,  2,         // 10
     6,  3,  2,         // 11
     7,  4,  2,         // 12
     8,  4,  2,         // 13
     9,  5,  3,         // 14
    10,  5,  3,         // 15
    11,  6,  3,         // 16
    12,  6,  3,         // 17
    14,  7,  4,         // 18
    15,  8,  4,         // 19
    16,  8,  5,         // 20
    17,  8,  5,         // 21
    18,  9,  5,         // 22
    19,  9,  6,         // 23
    20, 10,  6,         // 24
    21, 11,  6,         // 25
    22, 11,  7,         // 26
    23, 12,  7,         // 27
    24, 12,  8,         // 28
    25, 13,  8,         // 29
    26, 13,  8,         // 30
    27, 14,  9,         // 31
}};

// Table B.18: max_sfb_master[384], by row, to n_sfb_side[192], [96].
constexpr std::array<std::uint8_t, 32> kSfbSide384 = {{
     0,  0,             // 0
     1,  1,             // 1
     1,  1,             // 2
     2,  1,             // 3
     2,  1,             // 4
     3,  2,             // 5
     3,  2,             // 6
     4,  2,             // 7
     4,  2,             // 8
     5,  3,             // 9
     5,  3,             // 10
     6,  3,             // 11
     6,  3,             // 12
     7,  4,             // 13
     7,  4,             // 14
     8,  4,             // 15
}};

// Table B.19: max_sfb_master[192], by row, to n_sfb_side[96].
constexpr std::array<std::uint8_t, 8> kSfbSide192 = {{
     0,                 // 0
     1,                 // 1
     1,                 // 2
     2,                 // 3
     2,                 // 4
     3,                 // 5
     3,                 // 6
     4,                 // 7
}};

struct MasterTable {
    int master_length;
    std::array<int, 4> side_lengths;  // the n_sfb_side columns in order; 0 past them
    std::size_t columns;
    std::span<const std::uint8_t> values;  // [max_sfb_master * columns + column]
};

constexpr std::array<MasterTable, 12> kMasterTables = {{
    {2048, {{1024, 512, 256, 128}}, 4, kSfbSide2048},
    {1024, {{512, 256, 128, 0}}, 3, kSfbSide1024},
    {512, {{256, 128, 0, 0}}, 2, kSfbSide512},
    {256, {{128, 0, 0, 0}}, 1, kSfbSide256},
    {1920, {{960, 480, 240, 120}}, 4, kSfbSide1920},
    {960, {{480, 240, 120, 0}}, 3, kSfbSide960},
    {480, {{240, 120, 0, 0}}, 2, kSfbSide480},
    {240, {{120, 0, 0, 0}}, 1, kSfbSide240},
    {1536, {{768, 384, 192, 96}}, 4, kSfbSide1536},
    {768, {{384, 192, 96, 0}}, 3, kSfbSide768},
    {384, {{192, 96, 0, 0}}, 2, kSfbSide384},
    {192, {{96, 0, 0, 0}}, 1, kSfbSide192},
}};

const TransformLength* find_length(std::span<const TransformLength> table,
                                   int transform_length) noexcept {
    for (const TransformLength& entry : table) {
        if (entry.transform_length == transform_length) {
            return &entry;
        }
    }
    return nullptr;
}

}  // namespace

int num_sfb_48(int transform_length) noexcept {
    const TransformLength* entry = find_length(kTransformLengths, transform_length);
    return entry != nullptr ? entry->num_sfb : 0;
}

std::span<const std::uint16_t> sfb_offsets_48(int transform_length) noexcept {
    const TransformLength* entry = find_length(kTransformLengths, transform_length);
    return entry != nullptr ? entry->offsets : std::span<const std::uint16_t>{};
}

int num_sfb_96(int transform_length) noexcept {
    const TransformLength* entry = find_length(kTransformLengths96, transform_length);
    return entry != nullptr ? entry->num_sfb : 0;
}

std::span<const std::uint16_t> sfb_offsets_96(int transform_length) noexcept {
    const TransformLength* entry = find_length(kTransformLengths96, transform_length);
    return entry != nullptr ? entry->offsets : std::span<const std::uint16_t>{};
}

int num_sfb_192(int transform_length) noexcept {
    const TransformLength* entry = find_length(kTransformLengths192, transform_length);
    return entry != nullptr ? entry->num_sfb : 0;
}

std::span<const std::uint16_t> sfb_offsets_192(int transform_length) noexcept {
    const TransformLength* entry = find_length(kTransformLengths192, transform_length);
    return entry != nullptr ? entry->offsets : std::span<const std::uint16_t>{};
}

int max_sfb_from_master(int master_length, int max_sfb_master, int target_length) noexcept {
    const int num_sfb = num_sfb_48(master_length);
    if (num_sfb == 0 || max_sfb_master < 0) {
        return -1;
    }
    if (target_length == master_length) {
        return max_sfb_master <= num_sfb ? max_sfb_master : -1;
    }
    const auto row = static_cast<std::size_t>(max_sfb_master);
    for (const MasterTable& table : kMasterTables) {
        if (table.master_length != master_length) {
            continue;
        }
        if (row >= table.values.size() / table.columns) {
            return -1;
        }
        for (std::size_t column = 0; column < table.columns; ++column) {
            if (table.side_lengths[column] == target_length) {
                return table.values[row * table.columns + column];
            }
        }
        return -1;
    }
    return -1;
}

}  // namespace iclforge::ac4::detail::tables
