#pragma once

#include <array>
#include <cstdint>
#include <span>

// ETSI TS 103 190-1 V1.4.1 Annex C, the speech spectral frontend's tables (clause 5.2).
// GENERATED by tools/generators/gen_ac4_tables.py from the attachment
// ts_103190_tables.c and the text of Annex C; do not edit by hand.

namespace iclforge::ac4::detail::tables {

// Table C.1: the block lengths (n_mdct) it has columns for, and for each the width in
// lines of each of the 19 bands.
inline constexpr std::array<int, 8> kSsfBlockLengths = {192, 240, 256, 384, 512, 768, 960, 1024};
extern const std::array<std::array<std::uint8_t, 19>, 8> kSsfBandWidths;

// Tables C.2 and C.3, as the decimal text prints them, in double.
extern const std::array<double, 20> kSsfPostGainLut;
extern const std::array<double, 32> kSsfPredGainQuantTab;

// Tables C.4 and C.5, indexed by tab_idx.
extern const std::array<std::int8_t, 37> kSsfPredRfsTable;
extern const std::array<std::int8_t, 37> kSsfPredRtsTable;

// Annex C.6: ssf_pred_coeff_mat<tab_idx>, as the attachment lays them out. The layout
// is ((nu + Rf) * 33 + eta) * Rt + k, not the index of Pseudocode C.1
// (libs/ac4/ERRATA.md, "The layout of the SSF prediction coefficient tables").
extern const std::array<std::span<const std::uint8_t>, 37> kSsfPredCoeffQuantMat;

// Tables C.6 to C.9: CDF_TABLE (index -352 to 352 offset by 352), PREDICTOR_GAIN_CDF_LUT
// and ENVELOPE_CDF_LUT, in Q0.15.
extern const std::array<std::uint16_t, 705> kSsfCdfTable;
extern const std::array<std::uint16_t, 33> kSsfPredictorGainCdfLut;
extern const std::array<std::uint16_t, 33> kSsfEnvelopeCdfLut;

// Table C.9: DITHER_TABLE in Q0.15.
extern const std::array<std::uint16_t, 256> kSsfDitherTable;

// Tables C.11 and C.12: STEP_SIZES_Q4_15 and AC_COEFF_MAX_INDEX, by i_alloc.
extern const std::array<std::int32_t, 21> kSsfStepSizesQ4_15;
extern const std::array<std::uint8_t, 21> kSsfAcCoeffMaxIndex;

// Tables C.13 to C.16, the dB conversions of Pseudocodes 29 and 30.
extern const std::array<std::int16_t, 10> kSsfSlopesDbToLin;
extern const std::array<std::int16_t, 10> kSsfOffsetsDbToLin;
extern const std::array<std::int16_t, 50> kSsfSlopesLinToDb;
extern const std::array<std::int16_t, 50> kSsfOffsetsLinToDb;

}  // namespace iclforge::ac4::detail::tables
