from collections.abc import Sequence
from enum import Enum
from typing import Any, overload

import numpy as np
import numpy.typing as npt

__all__ = [
    "BLOCKS_PER_FRAME",
    "MAX_AC3_CHANNELS",
    "SAMPLES_PER_FRAME",
    "TRANSFORM_DELAY_SAMPLES",
    "Ac3DecodeError",
    "Ac3EncodeError",
    "Ac3Error",
    "Ac3ScanError",
    "Ac4DecodeError",
    "Ac4EncodeError",
    "Ac4Error",
    "AccessUnitTiming",
    "Acmod",
    "AtmosConfig",
    "AtmosEncoder",
    "CentreMixLevel",
    "DecodeError",
    "DecodedAccessUnit",
    "DecodedFrame",
    "DecodedProgram",
    "DecodedSubstream",
    "DecoderConfig",
    "DynamicObject",
    "Eac3Decoder",
    "EncoderConfig",
    "FrameDecoder",
    "FrameEncoder",
    "FrameError",
    "FrameHeader",
    "HeavyConfig",
    "LatencyBudget",
    "ObjectPlacement",
    "Position",
    "Profile",
    "ProfileId",
    "Program",
    "SampleRate",
    "ScanError",
    "ScannedProgramme",
    "ScannedStream",
    "StreamKind",
    "StreamType",
    "SubstreamService",
    "SurroundMixLevel",
    "__version__",
    "ac4",
    "access_unit_at_sample",
    "access_unit_at_seconds",
    "access_unit_timing",
    "build_codec_config_box",
    "containers",
    "describe",
    "eac3",
    "fullbw_channel_count",
    "meta",
    "profile_for",
    "profile_name",
    "read_frame_header",
    "sample_rate_hz",
    "scan",
    "signing",
    "split_access_units",
    "split_frames",
    "stream_bsid",
    "stream_duration_samples",
    "stream_duration_seconds",
    "uniform_access_unit_samples",
    "verify",
]

SAMPLES_PER_FRAME: int
BLOCKS_PER_FRAME: int
MAX_AC3_CHANNELS: int
TRANSFORM_DELAY_SAMPLES: int
__version__: str

_FloatArray = npt.NDArray[np.float32]
# Every encode_frame/encode_access_unit `channels`/`objects` parameter: either a
# single 2-D (n_channels, n_samples) array, or a sequence of 1-D per-channel arrays - both
# zero-copy when already contiguous float32 (see python-api.md's "Zero-copy numpy" section).
_ChannelsIn = _FloatArray | Sequence[_FloatArray]

class Ac3Error(RuntimeError): ...

class Ac3EncodeError(Ac3Error):
    error: FrameError

class Ac3DecodeError(Ac3Error):
    error: DecodeError

class Ac3ScanError(Ac3Error):
    error: ScanError

# AC-4's own failures (plan phase I4b): a ValueError, which is what ac3.ac4 raised before they had
# types of their own, so `except ValueError` still catches every one. `error` is the C++
# enumerator (ac4.DecodeError, ac4.EncodeError).
class Ac4Error(ValueError): ...

class Ac4DecodeError(Ac4Error):
    error: ac4.DecodeError

class Ac4EncodeError(Ac4Error):
    error: ac4.EncodeError

class Acmod(Enum):
    kDualMono = ...
    k1_0 = ...
    k2_0 = ...
    k3_0 = ...
    k2_1 = ...
    k3_1 = ...
    k2_2 = ...
    k3_2 = ...

class SampleRate(Enum):
    k48000 = ...
    k44100 = ...
    k32000 = ...
    k24000 = ...
    k22050 = ...
    k16000 = ...

class DecodeError(Enum):
    kTruncated = ...
    kBadSyncWord = ...
    kBadCrc = ...
    kReservedValue = ...
    kUnsupported = ...
    kInvalidStream = ...
    kNoReferenceTransform = ...

class FrameError(Enum):
    kInvalidBitrate = ...
    kInvalidDialnorm = ...
    kInvalidSubstream = ...
    kInvalidChannelMap = ...
    kTooManyChannels = ...
    kInvalidMixLevel = ...
    kInvalidBsi = ...
    kInvalidObjectAudio = ...

class StreamType(Enum):
    kIndependent = ...
    kDependent = ...
    kConvertible = ...

class StreamKind(Enum):
    kAc3 = ...
    kEac3 = ...
    kAc3CoreEac3Extension = ...

class ScanError(Enum):
    kEmpty = ...
    kLostSync = ...
    kUnsupportedBsid = ...
    kReservedValue = ...
    kTruncated = ...
    kUnsupportedStructure = ...

class ProfileId(Enum):
    kFilmStandard = ...
    kFilmLight = ...
    kMusicStandard = ...
    kMusicLight = ...
    kSpeech = ...

class CentreMixLevel(Enum):
    kMinus3dB = ...
    kMinus4_5dB = ...
    kMinus6dB = ...

class SurroundMixLevel(Enum):
    kMinus3dB = ...
    kMinus6dB = ...
    kSilent = ...

def fullbw_channel_count(acmod: Acmod) -> int: ...
def sample_rate_hz(sample_rate: SampleRate) -> int: ...
@overload
def describe(error: DecodeError) -> str: ...
@overload
def describe(error: ScanError) -> str: ...
@overload
def describe(error: FrameError) -> str: ...
def profile_for(id: ProfileId) -> Profile: ...
def profile_name(id: ProfileId) -> str: ...
def split_frames(stream: bytes) -> list[bytes]: ...
def split_access_units(stream: bytes) -> list[bytes]: ...
def stream_bsid(frame: bytes) -> int: ...

# scan() and friends - Python bindings completeness, iclforge::ac3::io/elementary.hpp.
def read_frame_header(at: bytes) -> FrameHeader: ...
def scan(stream: bytes) -> ScannedStream: ...
def access_unit_timing(stream: ScannedStream, index: int) -> AccessUnitTiming | None: ...
def stream_duration_samples(stream: ScannedStream) -> int: ...
def stream_duration_seconds(stream: ScannedStream) -> float: ...
def access_unit_at_sample(stream: ScannedStream, sample: int) -> int | None: ...
def access_unit_at_seconds(stream: ScannedStream, seconds: float) -> int | None: ...
def uniform_access_unit_samples(stream: ScannedStream) -> int | None: ...

class SubstreamService:
    @property
    def present(self) -> bool: ...
    @property
    def bsmod(self) -> int: ...
    @property
    def bsmod_present(self) -> bool: ...
    @property
    def acmod(self) -> Acmod: ...
    @property
    def lfe(self) -> bool: ...
    @property
    def mix_metadata(self) -> bool: ...

class FrameHeader:
    @property
    def kind(self) -> StreamKind: ...
    @property
    def bytes(self) -> int: ...
    @property
    def bsid(self) -> int: ...
    @property
    def bsmod(self) -> int: ...
    @property
    def bsmod_present(self) -> bool: ...
    @property
    def dsurmod(self) -> int: ...
    @property
    def sample_rate(self) -> SampleRate: ...
    @property
    def acmod(self) -> Acmod: ...
    @property
    def lfe(self) -> bool: ...
    @property
    def dialnorm(self) -> int: ...
    @property
    def compr(self) -> int | None: ...
    @property
    def dialnorm2(self) -> int | None: ...
    @property
    def compr2(self) -> int | None: ...
    @property
    def strmtyp(self) -> StreamType: ...
    @property
    def substreamid(self) -> int: ...
    @property
    def numblkscod(self) -> int: ...
    @property
    def reduced_rate(self) -> bool: ...
    @property
    def chanmap(self) -> int | None: ...
    @property
    def oba_complexity_index(self) -> int | None: ...
    @property
    def mix_metadata(self) -> bool: ...
    @property
    def bit_rate_code(self) -> int: ...
    @property
    def bitrate_kbps(self) -> int: ...
    @property
    def coded_channels(self) -> int: ...

class AccessUnitTiming:
    @property
    def start_sample(self) -> int: ...
    @property
    def duration_samples(self) -> int: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def start_seconds(self) -> float: ...
    @property
    def duration_seconds(self) -> float: ...
    def start_in_timescale(self, timescale: int) -> int: ...
    def duration_in_timescale(self, timescale: int) -> int: ...

class ScannedProgramme:
    @property
    def substreamid(self) -> int: ...
    @property
    def acmod(self) -> Acmod: ...
    @property
    def lfe(self) -> bool: ...
    @property
    def channels(self) -> int: ...
    @property
    def bsid(self) -> int: ...
    @property
    def bsmod(self) -> int: ...
    @property
    def substreams_per_unit(self) -> int: ...
    @property
    def oba_complexity_index(self) -> int | None: ...
    @property
    def access_units(self) -> list[bytes]: ...

class ScannedStream:
    @property
    def kind(self) -> StreamKind: ...
    @property
    def sample_rate(self) -> SampleRate: ...
    @property
    def acmod(self) -> Acmod: ...
    @property
    def lfe(self) -> bool: ...
    @property
    def channels(self) -> int: ...
    @property
    def access_units(self) -> list[bytes]: ...
    @property
    def access_unit_samples(self) -> list[int]: ...
    @property
    def substreams_per_unit(self) -> int: ...
    @property
    def programmes(self) -> list[ScannedProgramme]: ...
    @property
    def bsid(self) -> int: ...
    @property
    def bsmod(self) -> int: ...
    @property
    def bit_rate_code(self) -> int: ...
    @property
    def oba_complexity_index(self) -> int | None: ...
    @property
    def bsmod_present(self) -> bool: ...
    @property
    def dsurmod(self) -> int: ...
    @property
    def mix_metadata(self) -> bool: ...
    @property
    def independent_substreams(self) -> int: ...
    @property
    def associated_substreams(self) -> list[SubstreamService]: ...
    @property
    def channel_map(self) -> int: ...

class LatencyBudget:
    @property
    def frame_samples(self) -> int: ...
    @property
    def transform_samples(self) -> int: ...
    @property
    def lookahead_samples(self) -> int: ...
    @property
    def holdback_samples(self) -> int: ...
    @property
    def total_samples(self) -> int: ...
    def milliseconds(self, sample_rate: SampleRate) -> float: ...

class Profile:
    null_low_db: float
    null_high_db: float
    boost_ratio: float
    max_boost_db: float
    early_cut_ratio: float
    early_cut_end_db: float
    cut_ratio: float
    attack_ms: float
    release_ms: float
    def __init__(self, **kwargs: float) -> None: ...

class HeavyConfig:
    dialogue_target_dbfs: float
    peak_ceiling_dbfs: float
    release_db_per_second: float
    def __init__(self, **kwargs: float) -> None: ...

class Position:
    x: float
    y: float
    z: float
    def __init__(self, **kwargs: float) -> None: ...

class ObjectPlacement:
    position: Position
    gain: float
    lfe_send: float
    def __init__(self, **kwargs: object) -> None: ...

class DynamicObject:
    @property
    def position(self) -> Position: ...
    @property
    def gain_db(self) -> float: ...

class Program:
    @property
    def dynamic_only(self) -> bool: ...
    @property
    def lfe(self) -> bool: ...
    @property
    def bed(self) -> int: ...
    @property
    def dynamic_objects(self) -> int: ...

class DecodedProgram:
    @property
    def program(self) -> Program: ...
    @property
    def objects(self) -> list[DynamicObject]: ...

class EncoderConfig:
    sample_rate: SampleRate
    bitrate_kbps: int
    dialnorm: int
    dialnorm2: int | None
    chbwcod: int
    acmod: Acmod
    lfe: bool
    coupling: bool
    cplbegf: int
    cplendf: int
    fast_mdct: bool
    drc: Profile | None
    heavy: HeavyConfig | None
    drc2: Profile | None
    heavy2: HeavyConfig | None
    cmixlev: CentreMixLevel
    surmixlev: SurroundMixLevel
    def __init__(self, **kwargs: object) -> None: ...

class FrameEncoder:
    def __init__(self, config: EncoderConfig) -> None: ...
    def encode_frame(self, channels: _ChannelsIn) -> bytes: ...
    @property
    def config(self) -> EncoderConfig: ...
    @property
    def channel_count(self) -> int: ...
    @property
    def latency(self) -> LatencyBudget: ...
    @property
    def latency_samples(self) -> int: ...

class DecoderConfig:
    drc_scale: float
    heavy_compression: bool
    def __init__(self, **kwargs: object) -> None: ...

class DecodedFrame:
    @property
    def sample_rate(self) -> SampleRate: ...
    @property
    def bitrate_kbps(self) -> int: ...
    @property
    def acmod(self) -> Acmod: ...
    @property
    def lfe(self) -> bool: ...
    @property
    def dialnorm(self) -> int: ...
    @property
    def compr(self) -> int | None: ...
    @property
    def dialnorm2(self) -> int | None: ...
    @property
    def compr2(self) -> int | None: ...
    @property
    def dynrng(self) -> list[int]: ...
    @property
    def dynrng2(self) -> list[int]: ...
    @property
    def blksw(self) -> list[list[bool]]: ...
    @property
    def channels(self) -> list[_FloatArray]: ...
    @property
    def channel_labels(self) -> list[str]: ...

class DecodedSubstream:
    @property
    def strmtyp(self) -> StreamType: ...
    @property
    def substreamid(self) -> int: ...
    @property
    def sample_rate(self) -> SampleRate: ...
    @property
    def acmod(self) -> Acmod: ...
    @property
    def lfe(self) -> bool: ...
    @property
    def dialnorm(self) -> int: ...
    @property
    def compr(self) -> int | None: ...
    @property
    def dialnorm2(self) -> int | None: ...
    @property
    def compr2(self) -> int | None: ...
    @property
    def dynrng(self) -> list[int]: ...
    @property
    def dynrng2(self) -> list[int]: ...
    @property
    def numblkscod(self) -> int: ...
    @property
    def chanmap(self) -> int | None: ...
    @property
    def last_dependent(self) -> bool: ...
    @property
    def blksw(self) -> list[list[bool]]: ...
    @property
    def channels(self) -> list[_FloatArray]: ...
    @property
    def object_metadata(self) -> DecodedProgram | None: ...
    @property
    def object_audio(self) -> list[_FloatArray]: ...
    @property
    def channel_labels(self) -> list[str]: ...

class DecodedAccessUnit:
    @property
    def sample_rate(self) -> SampleRate: ...
    @property
    def acmod(self) -> Acmod: ...
    @property
    def dialnorm(self) -> int: ...
    @property
    def dialnorm2(self) -> int | None: ...
    @property
    def compr(self) -> int | None: ...
    @property
    def dynrng(self) -> list[int]: ...
    @property
    def numblkscod(self) -> int: ...
    @property
    def object_metadata(self) -> DecodedProgram | None: ...
    @property
    def object_audio(self) -> list[_FloatArray]: ...
    @property
    def substream_count(self) -> int: ...
    @property
    def channels(self) -> list[_FloatArray]: ...
    @property
    def channel_labels(self) -> list[str]: ...

class FrameDecoder:
    def __init__(self, config: DecoderConfig = ...) -> None: ...
    def decode_frame(self, frame: bytes) -> DecodedFrame: ...
    def decode_frame_into(self, frame: bytes, out: _ChannelsIn) -> DecodedFrame: ...
    @property
    def latency_samples(self) -> int: ...

class Eac3Decoder:
    def __init__(self, config: DecoderConfig = ...) -> None: ...
    def decode_substream(self, frame: bytes) -> DecodedSubstream | None: ...
    def decode_access_unit(self, unit: bytes) -> DecodedAccessUnit | None: ...
    def decode_access_unit_into(
        self, unit: bytes, out: _ChannelsIn
    ) -> DecodedAccessUnit | None: ...
    def flush(self) -> list[DecodedSubstream]: ...
    def __enter__(self) -> Eac3Decoder: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...
    @property
    def latency_samples(self) -> int: ...

# iclforge::ac3::verify - the encoder/decoder mirror trace and its research export. A real
# submodule (m.def_submodule) at runtime, stubbed as a nested-class namespace here for the same
# reason `eac3` below is. Pass a FrameTrace/Eac3AccessUnitTrace to DecoderConfig(trace=...)/
# (eac3_trace=...), decode, then read it back out with trace_to_csv/trace_to_json_lines.
class verify:
    class FrameTrace:
        def __init__(self) -> None: ...

    class Eac3AccessUnitTrace:
        def __init__(self) -> None: ...

    @staticmethod
    def trace_csv_header() -> str: ...
    @staticmethod
    def trace_to_csv(
        trace: verify.FrameTrace | verify.Eac3AccessUnitTrace, frame_index: int
    ) -> str: ...
    @staticmethod
    def trace_to_json_lines(
        trace: verify.FrameTrace | verify.Eac3AccessUnitTrace, frame_index: int
    ) -> str: ...

class AtmosConfig:
    sample_rate: SampleRate
    bitrate_kbps: int
    dialnorm: int
    num_bands_idx: int
    fine_quant: bool
    emit_object_metadata: bool
    fast_mdct: bool
    def __init__(self, **kwargs: object) -> None: ...

class AtmosEncoder:
    def __init__(self, config: AtmosConfig, objects: int) -> None: ...
    def encode_frame(self, objects: _ChannelsIn, placement: Sequence[ObjectPlacement]) -> bytes: ...
    @property
    def dynamic_object_count(self) -> int: ...
    @property
    def program(self) -> Program: ...
    @property
    def latency(self) -> LatencyBudget: ...
    @property
    def latency_samples(self) -> int: ...
    @property
    def bed_latency(self) -> LatencyBudget: ...

# iclforge::ac3::eac3::FrameEncoder/AccessUnitEncoder. A real submodule (m.def_submodule) at
# runtime, stubbed as a nested-class namespace here rather than a separate eac3.pyi, the way
# pybind11-stubgen represents one too - `iclforge.eac3.FrameConfig` resolves through this class the
# same way it resolves through the runtime module.
class eac3:
    MAX_RENDER_CHANNELS: int

    class LayoutId(Enum):
        kMono = ...
        kStereo = ...
        kDualMono = ...
        k51 = ...
        k71 = ...
        k512 = ...
        k514 = ...
        k714 = ...

    class FrameConfig:
        sample_rate: SampleRate
        bitrate_kbps: int
        numblkscod: int
        dialnorm: int
        dialnorm2: int | None
        chbwcod: int
        acmod: Acmod
        lfe: bool
        strmtyp: StreamType
        substreamid: int
        chanmap: int | None
        last_dependent: bool
        drc: Profile | None
        heavy: HeavyConfig | None
        drc2: Profile | None
        heavy2: HeavyConfig | None
        auto_tools: bool
        coupling: bool
        cplbegf: int
        enhanced: bool
        spx: bool
        spxbegf: int
        spx_atten: bool
        spxattencod: int
        aht: bool
        gaqmod: int
        transient_prenoise: bool
        fast_mdct: bool
        dither: bool
        oba_complexity_index: int | None
        def __init__(self, **kwargs: object) -> None: ...

    class FrameMetadata:
        dynrng: list[int]
        compr: int | None
        dynrng2: list[int]
        compr2: int | None
        def __init__(self, **kwargs: object) -> None: ...

    class AccessUnitConfig:
        independent: eac3.FrameConfig
        dependents: list[eac3.FrameConfig]
        def __init__(self, **kwargs: object) -> None: ...

    class AccessUnit:
        bytes: bytes
        substream_bytes: list[int]
        @property
        def substream_count(self) -> int: ...

    class FrameEncoder:
        def __init__(self, config: eac3.FrameConfig) -> None: ...
        def encode_frame(
            self,
            channels: _ChannelsIn,
            metadata: eac3.FrameMetadata | None = ...,
            aux: bytes = ...,
        ) -> bytes: ...
        @property
        def config(self) -> eac3.FrameConfig: ...
        @property
        def channel_count(self) -> int: ...
        @property
        def samples_per_frame(self) -> int: ...
        @property
        def latency(self) -> LatencyBudget: ...
        @property
        def latency_samples(self) -> int: ...

    class AccessUnitEncoder:
        def __init__(self, config: eac3.AccessUnitConfig) -> None: ...
        def encode_access_unit(
            self, channels: _ChannelsIn, aux: bytes = ...
        ) -> eac3.AccessUnit: ...
        @property
        def config(self) -> eac3.AccessUnitConfig: ...
        @property
        def channel_count(self) -> int: ...
        @property
        def latency(self) -> LatencyBudget: ...
        @property
        def latency_samples(self) -> int: ...

    @staticmethod
    def access_unit_config_for_layout(
        layout: eac3.LayoutId,
        bitrate_kbps: int,
        dependent_bitrate_kbps: int | None = ...,
        sample_rate: SampleRate = ...,
    ) -> eac3.AccessUnitConfig: ...


def build_codec_config_box(stream: bytes) -> bytes: ...

# iclforge::ac3::meta - loudness metering and QC. A real submodule at runtime, stubbed as a
# nested-class namespace exactly like `eac3` above.
class meta:
    class LoudnessMeter:
        def __init__(self, sample_rate: SampleRate, acmod: Acmod, lfe: bool) -> None: ...
        def push(self, channels: _ChannelsIn) -> None: ...
        @property
        def integrated_lkfs(self) -> float | None: ...
        @property
        def momentary_lkfs(self) -> float | None: ...
        @property
        def short_term_lkfs(self) -> float | None: ...
        @property
        def loudness_range(self) -> float | None: ...
        @property
        def true_peak_dbtp(self) -> float | None: ...
        @property
        def channel_count(self) -> int: ...

    class QcPresetId(Enum):
        kEbuR128S2 = ...
        kAtscA85 = ...
        kAtscA85Streaming = ...
        kNetflix = ...
        kAppleMusicAtmos = ...

    class QcLoudnessLimit(Enum):
        kBand = ...
        kCeiling = ...

    class QcPreset:
        target_lkfs: float
        tolerance_lu: float
        max_true_peak_dbtp: float
        loudness_limit: meta.QcLoudnessLimit
        @property
        def source(self) -> str: ...

    class QcVerdict:
        loudness_delta_lu: float | None
        loudness_pass: bool
        true_peak_margin_dbtp: float | None
        true_peak_pass: bool
        @property
        def passed(self) -> bool: ...

    @staticmethod
    def qc_preset(id: meta.QcPresetId) -> meta.QcPreset: ...
    @staticmethod
    def evaluate_qc_gate(
        preset: meta.QcPreset,
        integrated_lkfs: float | None,
        true_peak_dbtp: float | None,
    ) -> meta.QcVerdict: ...

# AC-4 decode/encode (plan phase I4) - iclforge::ac4::Decoder/iclforge::ac4::Encoder. Same
# submodule-as-class convention. A subset of both C++ headers - see
# python/src/iclforge_ext/ac4/present/ac4_module.cpp's own header comment for what is left out.
class ac4:
    class Speaker(Enum):
        kLeft = ...
        kRight = ...
        kCentre = ...
        kLfe = ...
        kLeftSurround = ...
        kRightSurround = ...
        kLeftBack = ...
        kRightBack = ...
        kLeftWide = ...
        kRightWide = ...
        kTopFrontLeft = ...
        kTopFrontRight = ...
        kTopBackLeft = ...
        kTopBackRight = ...
        kTopSideLeft = ...
        kTopSideRight = ...
        kLfe2 = ...
        kLeftScreen = ...
        kRightScreen = ...
        kTopFrontCentre = ...
        kTopBackCentre = ...
        kTopCentre = ...
        kBottomFrontLeft = ...
        kBottomFrontRight = ...
        kBottomFrontCentre = ...
        kCentreBack = ...

    class ObjectKind(Enum):
        kBed = ...
        kDyn = ...
        kIsf = ...

    class DownmixTarget(Enum):
        kAsCoded = ...
        k5X = ...
        kStereo = ...
        kLoRo = ...
        kLtRt = ...
        kMono = ...
        k7X4 = ...
        k7X2 = ...
        k7X0 = ...
        k5X4 = ...
        k5X2 = ...

    class DrcMode(Enum):
        kOff = ...
        kDefault = ...
        kHomeTheatre = ...
        kFlatPanelTv = ...
        kPortableSpeakers = ...
        kPortableHeadphones = ...

    class AssociatedType(Enum):
        kAny = ...
        kAudioDescription = ...
        kAudioDescriptionSubtitles = ...
        kSpokenSubtitles = ...
        kEmergencyInformation = ...

    class ConcealmentPolicy(Enum):
        kNone = ...
        kRepeatFade = ...
        kMute = ...

    class ConcealmentAction(Enum):
        kRepeatFade = ...
        kMute = ...

    class DecodeError(Enum):
        kTruncated = ...
        kInvalidToc = ...
        kInvalidStream = ...
        kUnsupported = ...
        kMissingIFrame = ...

    class DecodingMode(Enum):
        kFull = ...
        kCore = ...

    class CodecMode(Enum):
        kAuto = ...
        kSimple = ...
        kAspx = ...
        kAspxAcpl1 = ...
        kAspxAcpl2 = ...
        kAspxAcpl3 = ...
        kScpl = ...
        kAspxScpl = ...
        kAspxAjcc = ...

    class RateMode(Enum):
        kConstant = ...
        kAverage = ...
        kVariable = ...

    class EncodeError(Enum):
        kInvalidConfig = ...
        kInvalidInput = ...

    class BedChannel(Enum):
        kLeft = ...
        kRight = ...
        kCentre = ...
        kLeftSurround = ...
        kRightSurround = ...
        kLeftBack = ...
        kRightBack = ...
        kTopFrontLeft = ...
        kTopFrontRight = ...
        kTopSideLeft = ...
        kTopSideRight = ...
        kTopBackLeft = ...
        kTopBackRight = ...
        kLeftWide = ...
        kRightWide = ...

    class ObjectCoding(Enum):
        kAjoc = ...
        kDirect = ...

    class AjocDownmix(Enum):
        kComputed = ...
        kStatic50 = ...
        kStatic51 = ...

    class AdditionalPair(Enum):
        kNone = ...
        kBack = ...
        kWide = ...
        kTopFront = ...

    class OutputConfig:
        output_level_dbfs: float | None
        drc: ac4.DrcMode
        headphones: bool
        dialogue_enhancement_db: float
        downmix: ac4.DownmixTarget
        mix_lfe: bool
        dialogue_gain_db: float
        associated_gain_db: float
        def __init__(self, **kwargs: object) -> None: ...

    class PresentationChoice:
        presentation_id: int | None
        index: int | None
        language: str
        associated: int | None
        associated_type: ac4.AssociatedType
        headphones: bool
        def __init__(self, **kwargs: object) -> None: ...

    class DecoderConfig:
        output: ac4.OutputConfig
        concealment: ac4.ConcealmentPolicy
        presentation: ac4.PresentationChoice
        level: int
        decoding: ac4.DecodingMode
        def __init__(self, **kwargs: object) -> None: ...

    class Concealment:
        @property
        def error(self) -> ac4.DecodeError: ...
        @property
        def action(self) -> ac4.ConcealmentAction: ...

    class ObjectProperties:
        active: bool
        gain_db: float
        priority: float
        x: float
        y: float
        z: float
        zone_mask: int
        enable_elevation: bool
        snap: bool
        width_x: float
        width_y: float
        width_z: float
        screen_factor: float
        depth_exponent: float
        distance: float | None
        divergence: float
        trim_disabled: bool
        headphone_render_mode: int | None
        head_track_disabled: bool
        def __init__(self, **kwargs: object) -> None: ...

    class ObjectUpdate:
        @property
        def sample(self) -> int: ...
        @property
        def ramp_samples(self) -> int: ...
        @property
        def properties(self) -> ac4.ObjectProperties: ...

    class DecodedObject:
        @property
        def kind(self) -> ac4.ObjectKind: ...
        @property
        def lfe(self) -> bool: ...
        @property
        def speaker(self) -> ac4.Speaker | None: ...
        @property
        def samples(self) -> _FloatArray: ...
        @property
        def properties(self) -> ac4.ObjectProperties: ...
        @property
        def updates(self) -> list[ac4.ObjectUpdate]: ...

    class DecodedFrame:
        @property
        def sample_rate_hz(self) -> int: ...
        @property
        def sequence_counter(self) -> int: ...
        @property
        def presentation_index(self) -> int: ...
        @property
        def presentation_id(self) -> int | None: ...
        @property
        def speakers(self) -> list[ac4.Speaker]: ...
        @property
        def channels(self) -> list[_FloatArray]: ...
        @property
        def samples(self) -> int: ...
        @property
        def concealed(self) -> ac4.Concealment | None: ...
        @property
        def objects(self) -> list[ac4.DecodedObject]: ...

    class PresentationInfo:
        @property
        def index(self) -> int: ...
        @property
        def presentation_id(self) -> int | None: ...
        @property
        def md_compat(self) -> int | None: ...
        @property
        def enabled(self) -> bool: ...
        @property
        def alternative(self) -> bool: ...
        @property
        def pre_virtualized(self) -> bool: ...
        @property
        def name(self) -> str: ...
        @property
        def language(self) -> str: ...
        @property
        def decodable(self) -> bool: ...
        @property
        def selectable(self) -> bool: ...
        @property
        def speakers(self) -> list[ac4.Speaker]: ...

    class LoudnessInfo:
        @property
        def dialnorm_dbfs(self) -> float | None: ...
        @property
        def integrated_lkfs(self) -> float | None: ...
        @property
        def true_peak_dbtp(self) -> float | None: ...
        @property
        def loudness_range_lu(self) -> float | None: ...

    class Decoder:
        def __init__(self, config: ac4.DecoderConfig = ...) -> None: ...
        def decode(self, frame: bytes) -> ac4.DecodedFrame | None: ...
        def set_output(self, output: ac4.OutputConfig) -> None: ...
        @property
        def output(self) -> ac4.OutputConfig: ...
        def set_presentation(self, choice: ac4.PresentationChoice) -> None: ...
        @property
        def presentations(self) -> list[ac4.PresentationInfo]: ...
        @property
        def metadata_loudness(self) -> ac4.LoudnessInfo: ...
        @property
        def refusal_reason(self) -> str: ...
        @property
        def latency_samples(self) -> int: ...
        def reset(self) -> None: ...

    class ObjectConfig:
        bed: ac4.BedChannel | None
        lfe: bool
        properties: ac4.ObjectProperties
        def __init__(self, **kwargs: object) -> None: ...

    class ObjectsConfig:
        objects: list[ac4.ObjectConfig]
        coding: ac4.ObjectCoding
        downmix: ac4.AjocDownmix
        downmix_signals: int | None
        decorrelation: bool
        parameter_bands: int | None
        coarse: bool | None
        screen_size_ratio_code: int | None
        bed_object_chan_distribute: bool
        def __init__(self, **kwargs: object) -> None: ...

    class ObjectMetadataUpdate:
        object: int
        sample: int
        ramp_samples: int
        properties: ac4.ObjectProperties
        # `object` is a field of this class, so the builtin cannot be named here.
        def __init__(self, **kwargs: Any) -> None: ...

    class Experimental:
        aspx_balance: bool
        aspx_varvar: bool
        aspx_interleave: bool
        coding_configs: bool
        seven_x: ac4.AdditionalPair
        acpl: bool
        back_pair: bool
        ajcc: bool
        objects: bool
        def __init__(self, **kwargs: object) -> None: ...

    class EncoderConfig:
        channels: int
        sample_rate_hz: int
        frame_rate_index: int
        bitrate_kbps: int
        rate_mode: ac4.RateMode
        codec_mode: ac4.CodecMode
        iframe_interval: int
        dialnorm_db: float
        iframes: list[int]
        fragment_starts: list[int]
        experimental: ac4.Experimental
        objects: ac4.ObjectsConfig | None
        def __init__(self, **kwargs: object) -> None: ...

    class EncodedFrame:
        @property
        def data(self) -> bytes: ...
        @property
        def samples(self) -> int: ...
        @property
        def iframe(self) -> bool: ...

    class Toc:
        def build_dac4(self) -> bytes: ...
        def dac4_refusal(self) -> str: ...
        def media_timing(self) -> tuple[int, int] | None: ...
        def samples_per_frame(self) -> int | None: ...

    class Encoder:
        @staticmethod
        def create(config: ac4.EncoderConfig) -> ac4.Encoder: ...
        @staticmethod
        def refusal_reason(config: ac4.EncoderConfig) -> str: ...
        def encode(
            self,
            channels: _ChannelsIn,
            updates: Sequence[ac4.ObjectMetadataUpdate] = ...,
        ) -> list[ac4.EncodedFrame]: ...
        def flush(self) -> list[ac4.EncodedFrame]: ...
        @property
        def toc(self) -> ac4.Toc: ...
        @property
        def codec_mode(self) -> ac4.CodecMode: ...
        @property
        def delay_samples(self) -> int: ...
        @property
        def decoder_delay_samples(self) -> int: ...

    @staticmethod
    def sync_frame(raw_ac4_frame: bytes, crc: bool) -> bytes: ...

# iclforge::ac3::signing - EMDF object-layer signing. Same submodule-as-class convention.
class signing:
    class SigningKey:
        def __init__(self, content: bytes) -> None: ...
        @property
        def empty(self) -> bool: ...

    class VerifySummary:
        valid: int
        mismatch: int
        no_container: int
        @property
        def all_valid(self) -> bool: ...

    @staticmethod
    def load_signing_key(path: str = ...) -> signing.SigningKey: ...
    @staticmethod
    def sign_atmos_stream(stream: bytes, key: signing.SigningKey) -> tuple[bytes, int]: ...
    @staticmethod
    def has_authenticity_tag(frame: bytes) -> bool: ...
    @staticmethod
    def verify_atmos_stream(stream: bytes, key: signing.SigningKey) -> signing.VerifySummary: ...

# Matroska/MP4/MPEG-TS carriage (Python bindings completeness). Same submodule-as-class convention.
class containers:
    class MatroskaTrack:
        codec_id: str
        sample_rate: int
        channels: int
        samples_per_frame: int
        language: str
        def __init__(self, **kwargs: object) -> None: ...

    class Mp4Track:
        codec_id: str
        sample_rate: int
        channels: int
        samples_per_frame: int
        codec_config: bytes
        language: str
        rfc6381: str
        def __init__(self, **kwargs: object) -> None: ...

    class TsTrack:
        codec: containers.TsCodec
        sample_rate: int
        channels: int
        samples_per_frame: int
        def __init__(self, **kwargs: object) -> None: ...

    class TsCodec(Enum):
        kAc3 = ...
        kEac3 = ...
        kAc4 = ...

    class TsProfile(Enum):
        kDvb = ...
        kAtsc = ...

    @staticmethod
    def mux_matroska(track: containers.MatroskaTrack, frames: Sequence[bytes]) -> bytes: ...
    @staticmethod
    def mux_mp4(track: containers.Mp4Track, frames: Sequence[bytes]) -> bytes: ...
    @staticmethod
    def mux_mpegts(
        track: containers.TsTrack,
        frames: Sequence[bytes],
        profile: containers.TsProfile = ...,
    ) -> bytes: ...
    @staticmethod
    def demux_matroska(file: bytes) -> tuple[str, list[bytes]]: ...
    @staticmethod
    def demux_mp4(file: bytes) -> tuple[str, bytes, list[bytes]]: ...
    @staticmethod
    def demux_mpegts(file: bytes) -> tuple[containers.TsCodec, list[bytes]]: ...
