import QtQuick
import QtTest

import ForgeGui

// GUI localisation's own end-to-end proof: with ICLFORGE_GUI_LOCALE=xx set on this
// suite's ctest entry (apps/forge/gui/tests/qml.cmake), LanguageManager loads
// the pseudo-locale QA fixture (apps/forge/gui/assets/translations/forge_gui_xx.ts,
// generated by tools/generators/gen_pseudo_locale.py) instead of the system
// locale - see language_manager.cpp's applyInitialLanguage(). Every message
// lupdate found is mechanically decorated ("[Àccéntéd téxt ~~~]" - accented,
// bracketed, padded), so any qsTr() string reaching the screen must contain
// that decoration. This is what proves the whole chain - extraction, .ts,
// lrelease's .qm, the /i18n resource, QTranslator - actually runs, without
// depending on the six real languages' translation coverage being complete.
//
// A string that reaches the screen WITHOUT the decoration would mean it
// bypassed qsTr() entirely - the other thing this fixture exists to catch,
// per gen_pseudo_locale.py's own docstring.
TestCase {
    id: testCase
    name: "LocalisationPipeline"
    when: windowShown

    Component {
        id: mainWindowComponent
        Main {}
    }

    function test_pseudoLocaleIsActiveForThisSuite() {
        compare(languageManager.currentLanguage, "xx");
    }

    // The window title is qsTr("Forge — %1").arg(sourceLabel), itself
    // built from a second qsTr() ("no source") - reachable with no dialog
    // opened and no source loaded, so this needs nothing beyond creating
    // the window.
    function test_windowTitleIsPseudoDecorated() {
        const win = createTemporaryObject(mainWindowComponent, testCase);
        verify(win !== null);
        verify(win.title.indexOf("[") >= 0, "title not decorated: " + win.title);
        verify(win.title.indexOf("~") >= 0, "title not decorated: " + win.title);
    }

    // The Guided/Advanced/Expert tier control is always present regardless
    // of source state - SegmentedControl.qml's own Accessible.name mirrors
    // each segment's qsTr()'d label exactly (see that file), so reading it
    // here doubles as a check that the accessible name itself was built
    // from the live, translated label rather than a hardcoded English copy.
    function test_segmentedControlLabelIsPseudoDecorated() {
        const win = createTemporaryObject(mainWindowComponent, testCase);
        verify(win !== null);
        const guidedSeg = findChild(win.contentItem, "seg-guided");
        verify(guidedSeg !== null);
        verify(guidedSeg.Accessible.name.indexOf("[") >= 0,
               "segment label not decorated: " + guidedSeg.Accessible.name);
    }
}
