import QtQuick
import QtTest

import ForgeGui

TestCase {
    id: testCase
    name: "SourceLoading"
    when: windowShown

    Component {
        id: mainWindowComponent
        Main {}
    }

    // The same fixture apps/forge/gui/src/main.cpp's --smoke harness already trusts, so
    // the two can never disagree about what a "known good" WAV looks like.
    readonly property url fixtureUrl:
        Qt.resolvedUrl("../../../../../libs/base/fuzz/seeds/fuzz_wav_read/roundtrip-stereo.wav")
    // 44.1kHz, deliberately not the 48kHz every other fixture here is -
    // generated by tools/generators/gen_gui_resample_test_wav.py, a real two-tone
    // signal (see that script's own header on why silence would false-pass
    // the frequency check below).
    readonly property url mismatchedRateUrl:
        Qt.resolvedUrl("../../../../../libs/base/fuzz/seeds/fuzz_wav_read/resample-44100.wav")

    // The controller singleton is shared across every tst_*.qml file in this
    // binary - see tst_sweep_conformance.qml's own cleanup() and its
    // comment on why leaving a source loaded here would break another file.
    function cleanup() {
        if (EncoderController.sourceModel.length > 0) {
            EncoderController.removeSource(0);
        }
    }

    function test_loadingAFileUpdatesSourceReadyAndTheDisplayedName() {
        const win = createTemporaryObject(mainWindowComponent, testCase);
        verify(win !== null);
        compare(EncoderController.sourceReady, false);

        EncoderController.loadSourceFile(fixtureUrl);
        tryCompare(EncoderController, "sourceReady", true);

        compare(win.sourceLabel, "roundtrip-stereo.wav");
    }

    // Files whose header states which speakers their channels are (generated
    // by tools/generators/gen_gui_speaker_mask_wavs.py). The two three-channel
    // files are the pair a channel COUNT cannot tell apart: one is a 2/1
    // programme, the other states nothing and is read as L R C.
    readonly property url stated21Url: Qt.resolvedUrl("../fixtures/speakers-2-1.wav")
    readonly property url stated30LfeUrl: Qt.resolvedUrl("../fixtures/speakers-3-0-lfe.wav")
    readonly property url unstatedThreeUrl: Qt.resolvedUrl("../fixtures/speakers-none-3ch.wav")

    function bedId() {
        return EncoderController.bedChoices[EncoderController.bedIndex].id;
    }

    function test_aFileThatStatesItsSpeakersIsLoadedAsThatCodingMode() {
        const win = createTemporaryObject(mainWindowComponent, testCase);
        verify(win !== null);
        EncoderController.atmosEnabled = false;
        EncoderController.codecIndex = 0;  // AC-3: no substream layer, so the bed is all there is

        EncoderController.loadSourceFile(stated21Url);
        tryCompare(EncoderController, "sourceReady", true);
        // FL FR BC is 2/1 - a mode with no preset, which the width alone
        // (three channels) would have made a 5.1 with silent surrounds.
        compare(bedId(), "2/1");
        compare(EncoderController.bedLfe, false);
        compare(EncoderController.codedChannelCount, 3);
    }

    function test_aStatedLfeIsKeptNotMadeIntoAFifthFullBandwidthChannel() {
        const win = createTemporaryObject(mainWindowComponent, testCase);
        verify(win !== null);
        EncoderController.atmosEnabled = false;
        EncoderController.codecIndex = 0;

        EncoderController.loadSourceFile(stated30LfeUrl);
        tryCompare(EncoderController, "sourceReady", true);
        compare(bedId(), "3/0");
        compare(EncoderController.bedLfe, true);
        compare(EncoderController.codedChannelCount, 4);
    }

    function test_aFileThatStatesNoSpeakersKeepsTheReadingItsWidthGave() {
        const win = createTemporaryObject(mainWindowComponent, testCase);
        verify(win !== null);
        EncoderController.atmosEnabled = false;
        EncoderController.codecIndex = 0;

        EncoderController.loadSourceFile(unstatedThreeUrl);
        tryCompare(EncoderController, "sourceReady", true);
        // Three channels with no mask: L R C placed on a 5.1, as before.
        compare(bedId(), "3/2");
        compare(EncoderController.bedLfe, true);
        compare(EncoderController.codedChannelCount, 6);
    }

    function test_sourceLevelsIsAPerSourceLookupSeparateFromSourceModel() {
        const win = createTemporaryObject(mainWindowComponent, testCase);
        verify(win !== null);

        EncoderController.loadSourceFile(fixtureUrl);
        tryCompare(EncoderController, "sourceReady", true);
        // One loaded source, one pip - sourceLevels is index-aligned with
        // sourceModel, never folded into it (a Repeater binds to
        // sourceModel for row identity and looks a level up by index
        // instead - the same lookup-by-index pattern ChannelMeter's
        // delegate already uses against channelLevels).
        tryVerify(() => EncoderController.sourceLevels.length === 1);
        verify(EncoderController.sourceModel[0].peakDb === undefined);
        verify(EncoderController.sourceLevels[0].peakDb !== undefined);
        // Real, non-silent fixture content - the background pass having
        // landed reads as a peak above the meter floor, not stuck at it.
        tryVerify(() => EncoderController.sourceLevels[0].peakDb
                         > EncoderController.meterFloorDb);

        EncoderController.addSourceFile(fixtureUrl);
        tryVerify(() => EncoderController.sourceModel.length === 2);
        // Grows with the source list rather than staying at the stale
        // one-source length.
        tryVerify(() => EncoderController.sourceLevels.length === 2);

        EncoderController.removeSource(0);
        // Back to nothing loaded: reset synchronously (resetSourceLevels'
        // own contract), not left showing a stale reading under an empty
        // rail.
        compare(EncoderController.sourceLevels.length, 0);
    }

    function test_addingAMismatchedRateSourceResamplesAndLabelsTheRow() {
        const win = createTemporaryObject(mainWindowComponent, testCase);
        verify(win !== null);

        EncoderController.loadSourceFile(fixtureUrl);  // 48000 Hz, primary
        tryCompare(EncoderController, "sourceReady", true);
        compare(EncoderController.sourceModel[0].rate, 48000);

        // A mismatched rate is resampled onto the primary's, not refused -
        // see addSourceFile's own comment. The row reports the PRIMARY's
        // rate (its channels now actually carry that many samples/sec),
        // and resampleLabel says a conversion happened.
        EncoderController.addSourceFile(mismatchedRateUrl);
        tryVerify(() => EncoderController.sourceModel.length === 2);
        compare(EncoderController.sourceModel[1].rate, 48000);
        compare(EncoderController.sourceModel[1].resampleLabel, "44.1→48 k");
        // The primary's own row never resamples anything - there is
        // nothing for it to have been converted FROM.
        compare(EncoderController.sourceModel[0].resampleLabel, "");

        // A same-rate add carries no label at all - resampling only ever
        // shows up when it actually happened.
        EncoderController.addSourceFile(fixtureUrl);
        tryVerify(() => EncoderController.sourceModel.length === 3);
        compare(EncoderController.sourceModel[2].resampleLabel, "");
    }
}
