#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <fstream>
#include <numbers>
#include <span>
#include <string>
#include <utility>
#include <vector>

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include "iclforge/ac3/decoder/decoder.hpp"
#include "iclforge/objects/emdf.hpp"
#include "iclforge/ac3/oba/joc.hpp"
#include "iclforge/objects/oamd.hpp"

// The one Atmos bitstream in this repository that this project's own encoder
// did not make: a DD+ JOC stream from the Dolby Encoding Engine, generated by
// tools/generators/gen_object_fixture.py (see its header for what DEE was fed
// and why it is channel-based immersive rather than an ADM master).
//
// The point of this test is that the object layer used to refuse this
// stream outright, at four independent places - the EMDF payload
// configuration, the OAMD program assignment, the OAMD element count, and the
// JOC downmix configuration - so what these cases really assert is that none
// of those refusals is left.
//
// The last case is the load-bearing one. Every channel of the 5.1.4 bed DEE
// was given carries a different tone, so identifying each reconstructed JOC
// object by which tone dominates it says, independently of anything in this
// codebase, both that the reconstruction is right and that the bed's channel
// ORDER is right - and that order is the one §5.6.1.1.4 states backwards (see
// oba::bed_labels).

namespace {

constexpr const char* kFixture =
    ICLFORGE_GOLDEN_OBJECT_DIR "/dee_joc_514.ec3";

std::vector<std::byte> read_fixture() {
    std::ifstream in{kFixture, std::ios::binary};
    REQUIRE(in.good());
    const std::string bytes{std::istreambuf_iterator<char>{in},
                            std::istreambuf_iterator<char>{}};
    std::vector<std::byte> out(bytes.size());
    std::ranges::transform(bytes, out.begin(),
                           [](char c) { return static_cast<std::byte>(c); });
    return out;
}

// Goertzel-style projection onto one frequency: the magnitude of the signal's
// correlation with a complex exponential, normalized by length. Enough to say
// which of a handful of well-separated tones dominates, which is all this
// needs - a full spectrum would say no more.
double tone_magnitude(std::span<const float> signal, double frequency, double sample_rate) {
    double real = 0.0;
    double imag = 0.0;
    for (std::size_t n = 0; n < signal.size(); ++n) {
        const double phase =
            2.0 * std::numbers::pi * frequency * static_cast<double>(n) / sample_rate;
        real += static_cast<double>(signal[n]) * std::cos(phase);
        imag += static_cast<double>(signal[n]) * std::sin(phase);
    }
    return std::hypot(real, imag) / static_cast<double>(signal.size());
}

// gen_object_fixture.py's own table, in DEE's cbi_wav channel order.
struct BedChannel {
    const char* label;
    double frequency;
};
constexpr std::array<BedChannel, 10> kInput = {{
    {"L", 220.0}, {"R", 277.2}, {"C", 330.0}, {"LFE", 55.0}, {"Ls", 554.4},
    {"Rs", 660.0}, {"Ltf", 740.0}, {"Rtf", 831.6}, {"Ltr", 880.0}, {"Rtr", 1108.8},
}};

}  // namespace

TEST_CASE("the DEE fixture's EMDF container uses configurations Table 56 does not",
          "[oba][fixture]") {
    // Reaching the container means walking the audio blocks, so this goes
    // through the decoder rather than at the bytes directly - and that the
    // decode succeeds at all is itself the check on audblk's cplfgaincod,
    // which used to be skipped and desynchronised the frame three bits later.
    const auto data = read_fixture();
    const auto units = iclforge::ac3::split_access_units(data);
    REQUIRE(units.has_value());
    REQUIRE(units->size() > 3);  // real audio over more than three frames

    iclforge::ac3::Eac3Decoder decoder;
    const auto decoded = decoder.decode_access_unit(units->front());
    REQUIRE(decoded.has_value());
    REQUIRE(decoded->has_value());
    REQUIRE((*decoded)->object_metadata.has_value());
}

TEST_CASE("the DEE fixture's OAMD is a twelve-channel bed with a trim element",
          "[oba][fixture]") {
    const auto data = read_fixture();
    const auto units = iclforge::ac3::split_access_units(data);
    REQUIRE(units.has_value());

    iclforge::ac3::Eac3Decoder decoder;
    const auto decoded = decoder.decode_access_unit(units->front());
    REQUIRE(decoded.has_value());
    REQUIRE(decoded->has_value());
    const auto& program = *(*decoded)->object_metadata;

    // b_dyn_object_only_program 0 - the branch parse_payload used to refuse
    // outright for anything but a single standard instance with
    // b_bed_chan_distribute clear.
    CHECK_FALSE(program.program.dynamic_only);
    CHECK(program.program.bed_chan_distribute);
    CHECK(program.program.dynamic_objects == 0);
    CHECK(iclforge::objects::oba::object_count(program.program) == 12);
    CHECK(program.program.bed ==
          (iclforge::objects::oba::bed::kLR | iclforge::objects::oba::bed::kC |
           iclforge::objects::oba::bed::kLfe | iclforge::objects::oba::bed::kLsRs |
           iclforge::objects::oba::bed::kLbRb | iclforge::objects::oba::bed::kTflTfr |
           iclforge::objects::oba::bed::kTblTbr));

    // Two oa_elements, where exactly one used to be allowed.
    REQUIRE(program.trim.has_value());
    CHECK(program.trim->warp_mode == 1);
    CHECK(program.trim->global_trim_mode == 2);  // custom_trim
    CHECK(program.trim->configs.size() ==
          static_cast<std::size_t>(iclforge::objects::oba::kNumTrimConfigs));
    CHECK(program.trim->disable_per_object.size() == 12);
    CHECK(program.skipped_elements.empty());

    // One update block at offset 0, and the bed's own objects carry no render
    // info at all (§5.5.9), so nothing here should have invented positions.
    REQUIRE(program.blocks.size() == 1);
    CHECK(program.blocks.front().sample_offset == 0);
    CHECK(program.blocks.front().ramp_duration == 1536);
    CHECK(program.objects.empty());
}

TEST_CASE("the DEE fixture's JOC is sparse, phase-shifted and twelve-band",
          "[oba][fixture]") {
    // Straight at the payload: the decoder consumes JOC internally, so the
    // header fields it does not surface are only visible from here.
    const auto data = read_fixture();
    const auto units = iclforge::ac3::split_access_units(data);
    REQUIRE(units.has_value());

    iclforge::ac3::Eac3Decoder decoder;
    const auto decoded = decoder.decode_access_unit(units->front());
    REQUIRE(decoded.has_value());
    REQUIRE(decoded->has_value());
    // 12 bed channels less the LFE §6.3.2.2 bypasses.
    REQUIRE((*decoded)->object_audio.size() == 11);
    REQUIRE((*decoded)->object_indices.size() == 11);
    // The LFE is bed channel 3 in Table 12's descending order, so it is the
    // one index missing from the JOC outputs.
    CHECK(std::ranges::find((*decoded)->object_indices, 3) ==
          (*decoded)->object_indices.end());
}

TEST_CASE("every JOC object the DEE fixture reconstructs carries its own bed channel's tone",
          "[oba][fixture]") {
    const auto data = read_fixture();
    const auto units = iclforge::ac3::split_access_units(data);
    REQUIRE(units.has_value());

    iclforge::ac3::Eac3Decoder decoder;
    // Objects 5 and 6 are Lb/Rb: a 5.1.4 source has nothing for them, so DEE
    // fills them from Ls/Rs and they reconstruct as near-copies. They are
    // deliberately not asserted against a tone of their own.
    const std::array<const char*, 11> kExpected = {"L",  "R",   "C",   "Ls",  "Rs",  nullptr,
                                                   nullptr, "Ltf", "Rtf", "Ltr", "Rtr"};

    // Accumulate several frames per object: one frame is 1 536 samples, which
    // resolves 55 Hz barely at all, and the first frame has no previous matrix
    // to interpolate from (§6.6.5).
    std::vector<std::vector<float>> accumulated;
    int frames = 0;
    for (const auto& unit : *units) {
        const auto decoded = decoder.decode_access_unit(unit);
        REQUIRE(decoded.has_value());
        if (!decoded->has_value() || (*decoded)->object_audio.empty()) {
            continue;
        }
        ++frames;
        if (frames <= 4) {
            continue;  // skip the ramp-in
        }
        const auto& audio = (*decoded)->object_audio;
        if (accumulated.empty()) {
            accumulated.assign(audio.size(), {});
        }
        for (std::size_t i = 0; i < audio.size(); ++i) {
            accumulated[i].insert(accumulated[i].end(), audio[i].begin(), audio[i].end());
        }
        if (accumulated.front().size() >= 32768) {
            break;
        }
    }
    REQUIRE(accumulated.size() == 11);
    REQUIRE(accumulated.front().size() >= 32768);

    for (std::size_t object = 0; object < accumulated.size(); ++object) {
        const char* expected = kExpected[object];
        if (expected == nullptr) {
            continue;
        }
        std::size_t best = 0;
        double best_magnitude = -1.0;
        for (std::size_t channel = 0; channel < kInput.size(); ++channel) {
            const double magnitude =
                tone_magnitude(accumulated[object], kInput[channel].frequency, 48000.0);
            if (magnitude > best_magnitude) {
                best_magnitude = magnitude;
                best = channel;
            }
        }
        INFO("object " << object << " strongest tone is " << kInput[best].label
                       << ", expected " << expected);
        CHECK(std::string{kInput[best].label} == std::string{expected});
    }
}

// --- 7.1.4 and 9.1.6 ----------------------------------------------------------
//
// The 5.1.4 fixture says the bed's order is right for ten channels; these two
// say it holds for twelve and sixteen, where it is a different permutation
// from the order a production tool takes its INPUT in (9.1.6 puts the wides
// last in Table 12's bed and right after the rears at the input). Each
// fixture plays one input channel at a time, channel k alone in the k-th
// tenth of a second (gen_object_fixture.py), so the slice a reconstructed
// object is loud in names the input channel it came from, whatever the solver
// did with the rest - and the table below is the expectation written down
// independently of oba::bed_labels(): which INPUT slice carries each bed
// object, in the order the program lists them.

namespace {

constexpr std::size_t kSliceSamples = 4800;  // 0.1 s at 48 kHz

std::vector<std::byte> read_named(const char* name) {
    const std::string path = std::string{ICLFORGE_GOLDEN_OBJECT_DIR} + "/" + name;
    std::ifstream in{path, std::ios::binary};
    REQUIRE(in.good());
    const std::string bytes{std::istreambuf_iterator<char>{in}, std::istreambuf_iterator<char>{}};
    std::vector<std::byte> out(bytes.size());
    std::ranges::transform(bytes, out.begin(), [](char c) { return static_cast<std::byte>(c); });
    return out;
}

struct TdmDecode {
    iclforge::objects::oba::DecodedProgram program;
    // Every JOC object's audio over the whole stream, one vector each.
    std::vector<std::vector<float>> objects;
    std::vector<int> object_indices;
};

TdmDecode decode_tdm(const char* name, std::size_t expected_objects) {
    const auto data = read_named(name);
    const auto units = iclforge::ac3::split_access_units(data);
    REQUIRE(units.has_value());
    iclforge::ac3::Eac3Decoder decoder;
    TdmDecode out;
    out.objects.assign(expected_objects, {});
    bool have_program = false;
    for (const auto& unit : *units) {
        const auto decoded = decoder.decode_access_unit(unit);
        REQUIRE(decoded.has_value());
        REQUIRE(decoded->has_value());
        const auto& au = **decoded;
        if (!have_program && au.object_metadata.has_value()) {
            out.program = *au.object_metadata;
            out.object_indices = au.object_indices;
            have_program = true;
        }
        // An access unit that has no objects yet still occupies its 1 536
        // samples of the timeline, so the slices stay where the input put them.
        for (std::size_t i = 0; i < out.objects.size(); ++i) {
            if (i < au.object_audio.size()) {
                out.objects[i].insert(out.objects[i].end(), au.object_audio[i].begin(),
                                      au.object_audio[i].end());
            } else {
                out.objects[i].insert(out.objects[i].end(), 1536, 0.0F);
            }
        }
    }
    REQUIRE(have_program);
    return out;
}

// The input slice an object is loudest in, and by how many dB over the next.
std::pair<std::size_t, double> loudest_slice(std::span<const float> object, std::size_t slices) {
    std::vector<double> energy(slices, 0.0);
    for (std::size_t k = 0; k < slices; ++k) {
        for (std::size_t n = k * kSliceSamples;
             n < std::min((k + 1) * kSliceSamples, object.size()); ++n) {
            energy[k] += static_cast<double>(object[n]) * static_cast<double>(object[n]);
        }
    }
    std::size_t best = 0;
    for (std::size_t k = 1; k < slices; ++k) {
        if (energy[k] > energy[best]) {
            best = k;
        }
    }
    double second = 1e-30;
    for (std::size_t k = 0; k < slices; ++k) {
        if (k != best) {
            second = std::max(second, energy[k]);
        }
    }
    return {best, 10.0 * std::log10(std::max(energy[best], 1e-30) / second)};
}

}  // namespace

TEST_CASE("the DEE 7.1.4 fixture's bed is Table 12's twelve and each object is its own channel",
          "[oba][fixture][layouts]") {
    namespace oba = iclforge::objects::oba;
    const auto tdm = decode_tdm("dee_joc_714.ec3", 11);

    CHECK_FALSE(tdm.program.program.dynamic_only);
    CHECK(tdm.program.program.dynamic_objects == 0);
    CHECK(oba::object_count(tdm.program.program) == 12);
    CHECK(tdm.program.program.bed ==
          (oba::bed::kLR | oba::bed::kC | oba::bed::kLfe | oba::bed::kLsRs | oba::bed::kLbRb |
           oba::bed::kTflTfr | oba::bed::kTblTbr));
    CHECK(std::ranges::find(tdm.object_indices, 3) == tdm.object_indices.end());  // the LFE

    // Object i -> the input slice that carries it. The input order is
    // L R C LFE Ls Rs Lrs Rrs Ltf Rtf Ltr Rtr, so slice 3 (LFE) is nobody's
    // and the rest follow in order: Table 12's order IS the input order here.
    constexpr std::array<std::size_t, 11> kSlice = {0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11};
    const auto labels = oba::bed_labels(tdm.program.program.bed);
    REQUIRE(labels.size() == 12);
    for (std::size_t object = 0; object < kSlice.size(); ++object) {
        const auto [slice, dominance] = loudest_slice(tdm.objects[object], 12);
        INFO("object " << object << " (" << oba::describe(labels[object < 3 ? object : object + 1])
                       << ") is loudest in slice " << slice << ", expected " << kSlice[object]);
        CHECK(slice == kSlice[object]);
        CHECK(dominance > 3.0);
    }
}

TEST_CASE("the DEE 9.1.6 fixture's wides sit last in the bed and first among the heights at the "
          "input",
          "[oba][fixture][layouts]") {
    namespace oba = iclforge::objects::oba;
    const auto tdm = decode_tdm("dee_joc_916.ec3", 15);

    CHECK(oba::object_count(tdm.program.program) == 16);
    CHECK(tdm.program.program.bed ==
          (oba::bed::kLR | oba::bed::kC | oba::bed::kLfe | oba::bed::kLsRs | oba::bed::kLbRb |
           oba::bed::kTflTfr | oba::bed::kTslTsr | oba::bed::kTblTbr | oba::bed::kLwRw));
    CHECK(std::ranges::find(tdm.object_indices, 3) == tdm.object_indices.end());

    // The input order is L R C LFE Ls Rs Lrs Rrs Lw Rw Ltf Rtf Ltm Rtm Ltr Rtr;
    // Table 12 lists the bed L R C LFE Ls Rs Lb Rb Tfl Tfr Tsl Tsr Tbl Tbr Lw Rw.
    // So the JOC objects (the LFE bypassed) carry input slices
    //   L R C Ls Rs Lb Rb Tfl Tfr Tsl Tsr Tbl Tbr Lw Rw
    //   0 1 2 4  5  6  7  10  11  12  13  14  15  8  9
    // and the last two - the wides - are the ones that move.
    constexpr std::array<std::size_t, 15> kSlice = {0, 1, 2, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 8, 9};
    const auto labels = oba::bed_labels(tdm.program.program.bed);
    REQUIRE(labels.size() == 16);
    for (std::size_t object = 0; object < kSlice.size(); ++object) {
        const auto [slice, dominance] = loudest_slice(tdm.objects[object], 16);
        INFO("object " << object << " (" << oba::describe(labels[object < 3 ? object : object + 1])
                       << ") is loudest in slice " << slice << ", expected " << kSlice[object]);
        CHECK(slice == kSlice[object]);
        CHECK(dominance > 3.0);
    }
}
