#!/usr/bin/env python3
"""Generate the pages that describe the projects of the tree from tools/checks/projects.json.

    python3 tools/checks/generate_project_pages.py          # write the pages
    python3 tools/checks/generate_project_pages.py --check  # fail when one is stale

The table says, for every project, what it is (`purpose`), what kind, where it is, what it may use
and which CI lanes its tree lights. Two kinds of page follow from it, so that they cannot say
anything the table does not:

  - docs/projects.md: every project in one table, the graph of the libraries, and the exceptions;
  - <project>/README.md for a project that has no README of its own: what it is, what it uses and
    what uses it, where its code, tests and fuzz targets are, and how to build and test it alone.
    A README carries the marker line below; one without it is somebody's and is left alone.

Stdlib only. `--check` runs in the static job and in precheck.py.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from project_graph import Project, Table, load_table  # noqa: E402

MARKER = (
    "<!-- generated by tools/checks/generate_project_pages.py from tools/checks/projects.json; "
    "do not edit -->"
)
PAGE = "docs/projects.md"
TABLE_URL = "https://github.com/iainchesworthlabs/iclforge/blob/main/tools/checks/projects.json"

KIND_TITLE = {
    "library": "Libraries",
    "vendored": "Vendored code",
    "app-library": "Shared code of the programs",
    "app": "Programs",
    "binding": "Bindings",
    "firmware-library": "Firmware libraries",
    "firmware": "Firmware",
    "example": "Examples",
    "tests": "Tests",
}

INTRODUCTION = f"""\
The repository is a monorepo of projects: libraries under `libs/`, the programs of each product
under `apps/`, the code several programs compile in under `apps/shared/`, the language bindings
under `bindings/`, the firmware under `firmware/`, and the examples and cross-project tests. Every
one is a row of [`tools/checks/projects.json`]({TABLE_URL}), which says what it may use;
`check_layering.py` holds every `#include` and every CMake link line of the tree to it, and the CI
planners read the same rows to decide what a change builds ([CI lane partitions](ci-lanes.md)).
This page is generated from it.

A library uses only libraries. A program, a binding, a firmware project and an example use
libraries (a program also the shared code, a firmware project also the firmware library it is
built on) and never another program or firmware project, and no library uses a program. An
*internal* project is never installed, and no installed header includes one. A header another
project includes is under the project's `include/` or a directory its row exposes. Each project's
tests are beside it, and `ctest -L <project>` runs them.
"""


def users_of(table: Table, name: str) -> list[str]:
    return sorted(p.name for p in table.projects.values() if name in p.may_use)


def code(names: list[str] | tuple[str, ...]) -> str:
    return ", ".join(f"`{n}`" for n in names) if names else "nothing"


def page(table: Table) -> str:
    out = [MARKER, "", "# The projects of the tree", "", INTRODUCTION]
    for kind, title in KIND_TITLE.items():
        rows = [p for p in table.projects.values() if p.kind == kind]
        if not rows:
            continue
        out += [
            f"## {title}",
            "",
            "| Project | Path | What it is | Uses | Used by | CI lanes |",
            "|---|---|---|---|---|---|",
        ]
        for p in sorted(rows, key=lambda r: r.path):
            tag = " (internal)" if p.internal else ""
            out.append(
                f"| `{p.name}`{tag} | `{p.path}/` | {p.purpose} | {code(p.may_use)} | "
                f"{code(users_of(table, p.name))} | {', '.join(p.lanes)} |"
            )
        out.append("")
    out += ["## The libraries", "", "```mermaid", "flowchart LR"]
    libraries = [p for p in table.projects.values() if p.kind in ("library", "vendored")]
    ids = {p.name: p.name.replace("-", "_") for p in libraries}
    for p in sorted(libraries, key=lambda r: r.name):
        i = ids[p.name]
        out.append(f'    {i}(["{p.name}"])' if p.internal else f'    {i}["{p.name}"]')
    for p in sorted(libraries, key=lambda r: r.name):
        out.extend(f"    {ids[p.name]} --> {ids[used]}" for used in p.may_use if used in ids)
    out += ["```", "", "An arrow is *uses*; a rounded box is an internal library.", ""]
    if table.exceptions:
        out += [
            "## What the table allows by name",
            "",
            "Uses the kinds forbid and the tree has on purpose, each with its reason. One that",
            "excuses nothing fails the check.",
            "",
            "| From | To | Where | Why |",
            "|---|---|---|---|",
        ]
        for e in table.exceptions:
            where = ", ".join(f"`{x}`" for x in e.paths) or "any file"
            out.append(f"| `{e.source}` | `{e.target}` | {where} | {e.why} |")
        out.append("")
    return "\n".join(out)


def readme(table: Table, p: Project, has_tests: bool) -> str:
    kind = p.kind.replace("-", " ")
    out = [
        MARKER,
        "",
        f"# {p.name}",
        "",
        p.purpose,
        "",
        f"A {kind}, internal to the repository." if p.internal else f"A {kind}.",
        "",
        f"- **Uses:** {code(p.may_use)}",
        f"- **Used by:** {code(users_of(table, p.name))}",
        f"- **CI lanes:** {', '.join(p.lanes)}",
    ]
    if p.kind == "library":
        out += [f"- **CMake target:** `iclforge::{p.name}`"]
        out += [
            "",
            "## Layout",
            "",
            f"- `include/iclforge/{p.name}/`: the public headers",
            "- `src/`: the implementation and its private headers",
            "- `tests/`: its tests, one binary",
            "- `fuzz/`: its libFuzzer harnesses, with their seeds and regressions",
        ]
    out += ["", "## Build and test", "", "```sh"]
    out += ["cmake --preset config-linux-gcc && cmake --build --preset build-linux-gcc"]
    if has_tests:
        out += [f"ctest --preset test-linux-gcc -L {p.name}"]
    out += ["```", ""]
    out += [
        "All the projects are in the one CMake build"
        + ("; `ctest -L` runs this project's tests alone." if has_tests else "."),
        "",
        "The table of projects, what each uses and the rules it is held to:",
        "[`tools/checks/projects.json`](../../tools/checks/projects.json) and the",
        "[projects page](../../docs/projects.md).",
        "",
    ]
    return "\n".join(out)


def relink(path: str, text: str) -> str:
    """The relative links of a README reach out of its directory: one `../` for each level."""
    prefix = "../" * path.count("/")
    return text.replace("(../../tools/", f"({prefix}tools/").replace(
        "(../../docs/", f"({prefix}docs/"
    )


def outputs(root: Path, table: Table) -> dict[str, str]:
    files = {PAGE: page(table) + "\n"}
    for p in table.projects.values():
        target = f"{p.path}/README.md"
        if not (root / p.path).is_dir():
            continue
        existing = root / target
        if existing.is_file() and MARKER not in existing.read_text(encoding="utf-8"):
            continue  # somebody's own
        # ctest labels a project's tests with its name: a library's, an app-library's and a
        # product's, not a demo's (its tests are Playwright's) or a project that has none.
        ctest = p.kind in ("library", "app-library") or (
            p.kind == "app" and not p.path.startswith("apps/demos/")
        )
        has_tests = ctest and any(d.is_dir() for d in (root / p.path).glob("**/tests"))
        files[target] = relink(target, readme(table, p, has_tests))
    return files


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--root", type=Path, default=HERE.parents[1])
    ap.add_argument(
        "--check", action="store_true", help="fail when a generated page is not current"
    )
    args = ap.parse_args(argv)
    table = load_table(args.root / "tools" / "checks" / "projects.json")
    wanted = outputs(args.root, table)
    stale = []
    for relative, text in sorted(wanted.items()):
        path = args.root / relative
        have = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.is_file() else None
        if have == text:
            continue
        stale.append(relative)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    if args.check:
        for relative in stale:
            print(
                f"::error::generate_project_pages: {relative} is not current: run "
                "tools/checks/generate_project_pages.py"
            )
        print(f"generate_project_pages: {len(wanted)} pages, {len(stale)} stale")
        return 1 if stale else 0
    print(f"generate_project_pages: {len(wanted)} pages, {len(stale)} written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
