"""Emit the quarter-wave cosine table the AC-4 QMF banks' twiddle factors are built from.

Every rotation the QMF analysis and synthesis banks (src/ac4/src/core/dsp/qmf.cpp) and
their 64-point transform apply is a multiple of pi / 256: the pre- and post-rotations
are e^(i pi m / 64) and e^(+-i pi (2k + 1) / 256), the transform's factors
e^(2 pi i p k / 64) and e^(2 pi i p k / 16), and the synthesis's e^(-i pi (2k + 1) 255 /
256). So one table, cos(pi j / 256) for j = 0 to 128 (a quarter of the circle), gives
every one of them by an integer angle reduction
(src/ac4/src/core/dsp/qmf_constants.hpp), each the double nearest to the exact
value rather than what a platform's cos() and sin() return for an angle that has already been
rounded once.

The values are computed here in 60-digit decimal arithmetic (a Taylor series, with pi
to 80 digits) and rounded once to the nearest double, so the table does not depend on
the machine that ran the script, and each is written as the shortest decimal string
that reads back to the same double.

Run from the repo root:  python tools/generators/gen_ac4_qmf_twiddles.py
Check the committed header:  python tools/generators/gen_ac4_qmf_twiddles.py --check
"""

import argparse
import math
import sys
from decimal import Decimal, getcontext
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
OUT = REPO / "src" / "ac4" / "src" / "core" / "tables" / "qmf_twiddles.hpp"

STEPS = 256  # half the circle is 256 steps of pi / 256
ENTRIES = STEPS // 2 + 1  # j = 0 to 128

PI = Decimal(
    "3.14159265358979323846264338327950288419716939937510582097494459230781640628620899"
)


def decimal_cos(x: Decimal) -> Decimal:
    """cos(x) by its Taylor series, for the small |x| used here."""
    term = Decimal(1)
    total = Decimal(1)
    n = 0
    while True:
        n += 2
        term = -term * x * x / (Decimal(n - 1) * Decimal(n))
        if abs(term) < Decimal(10) ** -70:
            return total
        total += term


def table() -> list[float]:
    getcontext().prec = 60
    values = [float(decimal_cos(PI * j / STEPS)) for j in range(ENTRIES)]
    # The platform's cos() of the already rounded angle pi * j / 256 is off by up to
    # about 1.5e-16 itself; a disagreement beyond 3e-16 means the series is wrong.
    for j, value in enumerate(values):
        ref = math.cos(math.pi * j / STEPS)
        if abs(value - ref) > 3e-16:
            raise SystemExit(f"cos(pi {j} / {STEPS}) = {value!r}, but math.cos gives {ref!r}")
    # cos^2 + sin^2 = 1, with sin(pi j / 256) = cos(pi (128 - j) / 256).
    for j in range(ENTRIES):
        norm = values[j] ** 2 + values[ENTRIES - 1 - j] ** 2
        if abs(norm - 1.0) > 4e-16:
            raise SystemExit(f"cos^2 + sin^2 at j = {j} is {norm!r}")
    if values[0] != 1.0:
        raise SystemExit("cos(0) is not 1")
    # cos(pi / 2) is exactly 0; the series gives about 1e-60.
    if abs(values[-1]) > 1e-50:
        raise SystemExit("cos(pi / 2) is not 0")
    values[-1] = 0.0
    return values


def render(values: list[float]) -> str:
    lines = [
        "#pragma once",
        "",
        "#include <array>",
        "",
        "// GENERATED by tools/generators/gen_ac4_qmf_twiddles.py; do not edit by hand.",
        "//",
        "// cos(pi j / 256) for j = 0 to 128, a quarter of the circle, each the double nearest",
        "// to the exact value. Every twiddle factor of the QMF banks and their 64-point",
        "// transform is a multiple of pi / 256; dsp/qmf_constants.hpp builds them all from",
        "// this table by integer angle arithmetic, at compile time.",
        "",
        "namespace iclforge::ac4::detail::tables {",
        "",
        f"inline constexpr std::array<double, {ENTRIES}> kCosQuadrant = {{",
    ]
    row = "   "
    for value in values:
        text = repr(value) + ","
        if len(row) + 1 + len(text) > 98:
            lines.append(row)
            row = "   "
        row += " " + text
    lines.append(row)
    lines += ["};", "", "}  // namespace iclforge::ac4::detail::tables", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed header differs")
    args = parser.parse_args()
    text = render(table())
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(REPO)} is out of date; rerun this script", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(REPO)} is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({ENTRIES} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
