"""Golden-vector generator for the AC-3 analysis filterbank (Milestone 3).

Three independent anchors are tied together here:
1. Table 7.33 of ATSC A/52:2018 (the 256 published window values), parsed
   verbatim from the spec text extraction in spec/A52-2018.txt.
2. The Kaiser-Bessel-derived window computed from first principles with
   numpy (np.i0 Bessel kernel, alpha = 5 -> beta = 5*pi, kernel length 257).
   The script FAILS if this does not reproduce Table 7.33 to 5-decimal
   rounding, so a formula error can never silently become a golden.
3. The forward MDCT of A/52 section 8.2.3.2 evaluated directly in float64
   for a set of test signals, for both the long transform (alpha = 0,
   N = 512) and the two block-switched half transforms (alpha = -1/+1,
   N = 256 each, fed the same window-applied signal split in half — §7.9.2's
   "usual 512 sample windowed audio segment... split into two segments").
   The short-transform inverse (§7.9.4.2) has no separate golden here, same
   as the long inverse: both are validated by TDAC round-trip in
   libs/ac3/tests/core/test_mdct.cpp instead.

Output: testdata/mdct_goldens.hpp (constexpr arrays consumed by Catch2).
Run from the repo root:  python tools/generators/gen_mdct_goldens.py
"""

from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent.parent
SPEC_TXT = REPO / "spec" / "A52-2018.txt"
OUT = REPO / "testdata" / "mdct_goldens.hpp"

N = 512  # long-transform length


def parse_table_7_33() -> np.ndarray:
    """Parse the 256 window values of Table 7.33 from the spec extraction."""
    lines = SPEC_TXT.read_text(encoding="utf-8").splitlines()
    start = next(i for i, line in enumerate(lines)
                 if "Table 7.33 Transform Window Sequence" in line
                 and "A=0" in "".join(lines[i:i + 8]))
    values: list[float] = []
    for line in lines[start:start + 40]:
        stripped = line.strip()
        if stripped.startswith("A="):
            row = stripped.split()[1:]  # drop the "A=n" label
            values.extend(float(v) for v in row)
        if len(values) >= 256:
            break
    if len(values) != 256:
        raise SystemExit(f"Table 7.33 parse failed: got {len(values)} values, expected 256")
    return np.array(values)


def kbd_window_512() -> np.ndarray:
    """KBD window, alpha=5 (beta=5*pi), 512 points, from first principles."""
    beta = 5.0 * np.pi
    m = N // 2 + 1  # Kaiser kernel length 257
    i = np.arange(m)
    kernel = np.i0(beta * np.sqrt(1.0 - (2.0 * i / (m - 1) - 1.0) ** 2)) / np.i0(beta)
    cumulative = np.cumsum(kernel)
    half = np.sqrt(cumulative[:-1] / cumulative[-1])  # 256 values
    return np.concatenate([half, half[::-1]])


def mdct_forward(x_windowed: np.ndarray, n_len: int = N, alpha: float = 0.0) -> np.ndarray:
    """A/52 section 8.2.3.2: XD[k] = (-2/n_len) sum x[n] cos(phase(alpha))."""
    nn = np.arange(n_len)[None, :]
    k = np.arange(n_len // 2)[:, None]
    phase = ((2.0 * np.pi / (4.0 * n_len)) * (2 * nn + 1) * (2 * k + 1) +
             (np.pi / 4.0) * (2 * k + 1) * (1.0 + alpha))
    return (-2.0 / n_len) * np.sum(x_windowed[None, :] * np.cos(phase), axis=1)


def fmt_array(name: str, values: np.ndarray, per_line: int = 4) -> str:
    body = []
    for i in range(0, len(values), per_line):
        chunk = ", ".join(f"{v:.17g}" for v in values[i:i + per_line])
        body.append(f"    {chunk},")
    return (f"inline constexpr std::array<double, {len(values)}> {name} = {{\n"
            + "\n".join(body) + "\n};\n")


def main() -> None:
    table = parse_table_7_33()
    window = kbd_window_512()

    # Anchor 1 <-> 2: the formula must reproduce the published table.
    max_err = np.max(np.abs(np.round(window[:256], 5) - table))
    if max_err > 1e-9:  # after 5-decimal rounding the match must be exact
        raise SystemExit(f"KBD formula does not reproduce Table 7.33 (max err {max_err})")
    print(f"Table 7.33 check: formula reproduces all 256 values (post-rounding err {max_err})")

    rng = np.random.default_rng(0x0B77)
    signals = {
        "kGoldenImpulse0": np.zeros(N),
        "kGoldenImpulse100": np.zeros(N),
        "kGoldenDc": np.ones(N) * 0.5,
        "kGoldenSine": 0.9 * np.sin(2.0 * np.pi * 1000.0 / 48000.0 * np.arange(N)),
        "kGoldenRandom": rng.uniform(-1.0, 1.0, N),
    }
    signals["kGoldenImpulse0"][0] = 1.0
    signals["kGoldenImpulse100"][100] = 1.0

    parts = [
        "// GENERATED by tools/generators/gen_mdct_goldens.py - do not edit by hand.",
        "// Window values originate in ATSC A/52:2018 Table 7.33; MDCT vectors are",
        "// float64 evaluations of the section 8.2.3.2 equation on window-applied",
        "// inputs, for the long transform (alpha = 0, N = 512) and, per signal,",
        "// the pair of block-switched half transforms (alpha = -1/+1, N = 256,",
        "// fed the same window-applied signal split at its midpoint).",
        "#pragma once",
        "",
        "#include <array>",
        "",
        "namespace iclforge::golden {",
        "",
        fmt_array("kTable733", table, per_line=8),
        fmt_array("kKbdWindow512", window),
    ]
    for name, signal in signals.items():
        windowed = signal * window
        coeffs = mdct_forward(windowed, N, 0.0)
        short1 = mdct_forward(windowed[:256], 256, -1.0)
        short2 = mdct_forward(windowed[256:], 256, 1.0)
        parts.append(fmt_array(name + "Input", signal))
        parts.append(fmt_array(name + "Coeffs", coeffs))
        parts.append(fmt_array(name + "Short1Coeffs", short1))
        parts.append(fmt_array(name + "Short2Coeffs", short2))
    parts.append("}  // namespace iclforge::golden")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
