"""The AC-4 decoder's fixed-point tables (planning/ac4.md, D14d), from the float tables already
in the tree.

libs/dsp/src/tiered/tables/qmf_tables.cpp holds QWIN (Annex D.3) and ASPX_NOISE (Annex D.2) in the
float the attachment ts_103190_tables.c declares; tools/generators/gen_ac4_tables.py writes it
from the attachment. This reads those float literals back, rounds each float to an integer
format, and writes libs/dsp/src/tiered/tables/qmf_tables_fixed.hpp:

  kQwinQ30        QWIN in Q1.30, for the fixed-point QMF banks' 64-bit window sums;
  kAspxNoiseQ24   ASPX_NOISE as Fixed32's raw Q7.24, for A-SPX's noise generator.

Each value is the float's own value times 2^30 or 2^24, rounded half away from zero, so the
tables follow the committed ones and need no attachment. The header carries the largest sum
of the window's taps one output of each bank takes, which bounds the sums against wrapping.

Usage:
    gen_ac4_fixed_tables.py [--check]

--check fails, writing nothing, when the header is not what this would write.
"""

from __future__ import annotations

import math
import re
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _header_gen import wrap, write_or_check

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SOURCE = REPO_ROOT / "src" / "dsp" / "src" / "tiered" / "tables" / "qmf_tables.cpp"
HEADER = (
    REPO_ROOT
    / "src"
    / "dsp"
    / "src"
    / "tiered"
    / "tables"
    / "qmf_tables_fixed.hpp"
)

QWIN = re.compile(r"kQwin\s*=\s*\{([^{}]*)\}\s*;")
NOISE = re.compile(r"kAspxNoise\s*=\s*\{\{(.*?)\}\}\s*;", re.S)
PAIR = re.compile(r"\{\s*([^,{}]+?)\s*,\s*([^,{}]+?)\s*\}")


def as_float32(literal: str) -> float:
    text = literal.strip().rstrip("fF")
    return struct.unpack("<f", struct.pack("<f", float(text)))[0]


def to_integer(value: float, fraction_bits: int) -> int:
    scaled = value * (1 << fraction_bits)  # exact: a float times a power of two
    magnitude = math.floor(abs(scaled) + 0.5)
    result = -magnitude if scaled < 0 else magnitude
    if not -(1 << 31) <= result < (1 << 31):
        sys.exit(f"{value} does not fit Q{31 - fraction_bits}.{fraction_bits}")
    return result


def render() -> str:
    source = SOURCE.read_text(encoding="utf-8")
    qwin_match = QWIN.search(source)
    noise_match = NOISE.search(source)
    if qwin_match is None or noise_match is None:
        sys.exit(f"{SOURCE.relative_to(REPO_ROOT)}: no kQwin or kAspxNoise table")
    qwin = [as_float32(x) for x in qwin_match.group(1).split(",") if x.strip()]
    noise = [(as_float32(a), as_float32(b)) for a, b in PAIR.findall(noise_match.group(1))]
    if len(qwin) != 640 or len(noise) != 512:
        sys.exit(f"kQwin holds {len(qwin)} values and kAspxNoise {len(noise)}, not 640 and 512")
    analysis = max(sum(abs(qwin[128 * k + n]) for k in range(5)) for n in range(128))
    synthesis = max(
        sum(abs(qwin[128 * k + sb]) + abs(qwin[128 * k + 64 + sb]) for k in range(5))
        for sb in range(64)
    )
    lines = [
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "// The fixed-point tier's QWIN and ASPX_NOISE (planning/ac4.md, D14d). GENERATED by",
        "// tools/generators/gen_ac4_fixed_tables.py from the float tables of",
        "// libs/dsp/src/tiered/tables/qmf_tables.cpp; do not edit by hand.",
        "",
        "namespace iclforge::dsp::tiered::tables {",
        "",
        "// QWIN in Q1.30: each float of kQwin times 2^30, rounded half away from zero. One output",
        "// of the analysis sums five taps whose magnitudes add to at most "
        f"{analysis:.6f}, and one",
        "// of the synthesis ten whose magnitudes add to at most "
        f"{synthesis:.6f}, so a sum of their",
        "// products with values of Q7.24 is below 2^62 in magnitude on any input.",
        "inline constexpr std::array<std::int32_t, 640> kQwinQ30 = {",
        *wrap([str(to_integer(v, 30)) for v in qwin]),
        "};",
        "",
        "// ASPX_NOISE as Fixed32's raw Q7.24, {real, imaginary}: each float of kAspxNoise times",
        "// 2^24, rounded half away from zero.",
        "inline constexpr std::array<std::array<std::int32_t, 2>, 512> kAspxNoiseQ24 = {{",
        *wrap([f"{{{to_integer(a, 24)}, {to_integer(b, 24)}}}" for a, b in noise]),
        "}};",
        "",
        "}  // namespace iclforge::dsp::tiered::tables",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    return write_or_check(
        __doc__.split("\n\n")[0],
        render,
        HEADER,
        REPO_ROOT,
        "tools/generators/gen_ac4_fixed_tables.py",
    )


if __name__ == "__main__":
    sys.exit(main())
