#pragma once

#include <array>
#include <span>

#include "iclforge/ac4core/huffman_codebook.hpp"

// Every Huffman codebook of ETSI TS 103 190-1 V1.4.1 Annex A, and the A-JCC
// and A-JOC codebooks of ETSI TS 103 190-2 V1.3.1 Annex A.1, in index order,
// for writing: the codeword and its length for each index huff_decode()
// returns.
// GENERATED by tools/generators/gen_ac4_tables.py with huffman_tables.hpp,
// from the attachments ts_103190_tables.c and ts_103190_tables_part2.c; do
// not edit by hand. The decoder reads through huffman_tables.hpp and does not
// link these.

namespace iclforge::ac4::detail::tables {

// A.1: ASF.
extern const std::array<HuffCode, 121> kAsfHcbScalefacCodes;
extern const std::array<HuffCode, 81> kAsfHcb1Codes;
extern const std::array<HuffCode, 81> kAsfHcb2Codes;
extern const std::array<HuffCode, 81> kAsfHcb3Codes;
extern const std::array<HuffCode, 81> kAsfHcb4Codes;
extern const std::array<HuffCode, 81> kAsfHcb5Codes;
extern const std::array<HuffCode, 81> kAsfHcb6Codes;
extern const std::array<HuffCode, 64> kAsfHcb7Codes;
extern const std::array<HuffCode, 64> kAsfHcb8Codes;
extern const std::array<HuffCode, 169> kAsfHcb9Codes;
extern const std::array<HuffCode, 169> kAsfHcb10Codes;
extern const std::array<HuffCode, 289> kAsfHcb11Codes;
extern const std::array<HuffCode, 22> kAsfHcbSnfCodes;

// The spectrum codebooks by number, as kAsfSpectrumCodebooks has them;
// index 0 is empty.
extern const std::array<std::span<const HuffCode>, 12> kAsfSpectrumCodes;

// A.2: A-SPX.
extern const std::array<HuffCode, 71> kAspxHcbEnvLevel15F0Codes;
extern const std::array<HuffCode, 141> kAspxHcbEnvLevel15DfCodes;
extern const std::array<HuffCode, 141> kAspxHcbEnvLevel15DtCodes;
extern const std::array<HuffCode, 25> kAspxHcbEnvBalance15F0Codes;
extern const std::array<HuffCode, 49> kAspxHcbEnvBalance15DfCodes;
extern const std::array<HuffCode, 49> kAspxHcbEnvBalance15DtCodes;
extern const std::array<HuffCode, 36> kAspxHcbEnvLevel30F0Codes;
extern const std::array<HuffCode, 71> kAspxHcbEnvLevel30DfCodes;
extern const std::array<HuffCode, 71> kAspxHcbEnvLevel30DtCodes;
extern const std::array<HuffCode, 13> kAspxHcbEnvBalance30F0Codes;
extern const std::array<HuffCode, 25> kAspxHcbEnvBalance30DfCodes;
extern const std::array<HuffCode, 25> kAspxHcbEnvBalance30DtCodes;
extern const std::array<HuffCode, 30> kAspxHcbNoiseLevelF0Codes;
extern const std::array<HuffCode, 59> kAspxHcbNoiseLevelDfCodes;
extern const std::array<HuffCode, 59> kAspxHcbNoiseLevelDtCodes;
extern const std::array<HuffCode, 13> kAspxHcbNoiseBalanceF0Codes;
extern const std::array<HuffCode, 25> kAspxHcbNoiseBalanceDfCodes;
extern const std::array<HuffCode, 25> kAspxHcbNoiseBalanceDtCodes;

// A.3: A-CPL.
extern const std::array<HuffCode, 17> kAcplHcbAlphaCoarseF0Codes;
extern const std::array<HuffCode, 33> kAcplHcbAlphaFineF0Codes;
extern const std::array<HuffCode, 33> kAcplHcbAlphaCoarseDfCodes;
extern const std::array<HuffCode, 65> kAcplHcbAlphaFineDfCodes;
extern const std::array<HuffCode, 33> kAcplHcbAlphaCoarseDtCodes;
extern const std::array<HuffCode, 65> kAcplHcbAlphaFineDtCodes;
extern const std::array<HuffCode, 5> kAcplHcbBetaCoarseF0Codes;
extern const std::array<HuffCode, 9> kAcplHcbBetaFineF0Codes;
extern const std::array<HuffCode, 9> kAcplHcbBetaCoarseDfCodes;
extern const std::array<HuffCode, 17> kAcplHcbBetaFineDfCodes;
extern const std::array<HuffCode, 9> kAcplHcbBetaCoarseDtCodes;
extern const std::array<HuffCode, 17> kAcplHcbBetaFineDtCodes;
extern const std::array<HuffCode, 9> kAcplHcbBeta3CoarseF0Codes;
extern const std::array<HuffCode, 17> kAcplHcbBeta3FineF0Codes;
extern const std::array<HuffCode, 17> kAcplHcbBeta3CoarseDfCodes;
extern const std::array<HuffCode, 33> kAcplHcbBeta3FineDfCodes;
extern const std::array<HuffCode, 17> kAcplHcbBeta3CoarseDtCodes;
extern const std::array<HuffCode, 33> kAcplHcbBeta3FineDtCodes;
extern const std::array<HuffCode, 21> kAcplHcbGammaCoarseF0Codes;
extern const std::array<HuffCode, 41> kAcplHcbGammaFineF0Codes;
extern const std::array<HuffCode, 41> kAcplHcbGammaCoarseDfCodes;
extern const std::array<HuffCode, 81> kAcplHcbGammaFineDfCodes;
extern const std::array<HuffCode, 41> kAcplHcbGammaCoarseDtCodes;
extern const std::array<HuffCode, 81> kAcplHcbGammaFineDtCodes;

// A.4: dialogue enhancement.
extern const std::array<HuffCode, 32> kDeHcbAbs0Codes;
extern const std::array<HuffCode, 63> kDeHcbDiff0Codes;
extern const std::array<HuffCode, 61> kDeHcbAbs1Codes;
extern const std::array<HuffCode, 121> kDeHcbDiff1Codes;

// A.5: DRC.
extern const std::array<HuffCode, 255> kDrcHcbCodes;

// Part 2 A.1.2: A-JCC.
extern const std::array<HuffCode, 12> kAjccHcbDryCoarseF0Codes;
extern const std::array<HuffCode, 23> kAjccHcbDryFineF0Codes;
extern const std::array<HuffCode, 23> kAjccHcbDryCoarseDfCodes;
extern const std::array<HuffCode, 45> kAjccHcbDryFineDfCodes;
extern const std::array<HuffCode, 23> kAjccHcbDryCoarseDtCodes;
extern const std::array<HuffCode, 45> kAjccHcbDryFineDtCodes;
extern const std::array<HuffCode, 21> kAjccHcbWetCoarseF0Codes;
extern const std::array<HuffCode, 41> kAjccHcbWetFineF0Codes;
extern const std::array<HuffCode, 41> kAjccHcbWetCoarseDfCodes;
extern const std::array<HuffCode, 81> kAjccHcbWetFineDfCodes;
extern const std::array<HuffCode, 41> kAjccHcbWetCoarseDtCodes;
extern const std::array<HuffCode, 81> kAjccHcbWetFineDtCodes;

// Part 2 A.1.1: A-JOC.
extern const std::array<HuffCode, 51> kAjocHcbDryCoarseF0Codes;
extern const std::array<HuffCode, 101> kAjocHcbDryFineF0Codes;
extern const std::array<HuffCode, 51> kAjocHcbDryCoarseDfCodes;
extern const std::array<HuffCode, 101> kAjocHcbDryFineDfCodes;
extern const std::array<HuffCode, 101> kAjocHcbDryCoarseDtCodes;
extern const std::array<HuffCode, 201> kAjocHcbDryFineDtCodes;
extern const std::array<HuffCode, 21> kAjocHcbWetCoarseF0Codes;
extern const std::array<HuffCode, 41> kAjocHcbWetFineF0Codes;
extern const std::array<HuffCode, 21> kAjocHcbWetCoarseDfCodes;
extern const std::array<HuffCode, 41> kAjocHcbWetFineDfCodes;
extern const std::array<HuffCode, 41> kAjocHcbWetCoarseDtCodes;
extern const std::array<HuffCode, 81> kAjocHcbWetFineDtCodes;

}  // namespace iclforge::ac4::detail::tables
