#pragma once

#include <array>

#include "iclforge/ac4core/huffman_codebook.hpp"

// Every Huffman codebook of ETSI TS 103 190-1 V1.4.1 Annex A, and the A-JCC and
// A-JOC codebooks of ETSI TS 103 190-2 V1.3.1 Annex A.1. GENERATED by
// tools/generators/gen_ac4_tables.py from the attachments ts_103190_tables.c and
// ts_103190_tables_part2.c and the two annexes' text; do not edit by hand.

namespace iclforge::ac4::detail::tables {

// A.1: ASF.
extern const Codebook kAsfHcbScalefac;  // Table A.1
extern const Codebook kAsfHcb1;         // Tables A.2 to A.12: the spectrum codebooks 1 to 11
extern const Codebook kAsfHcb2;
extern const Codebook kAsfHcb3;
extern const Codebook kAsfHcb4;
extern const Codebook kAsfHcb5;
extern const Codebook kAsfHcb6;
extern const Codebook kAsfHcb7;
extern const Codebook kAsfHcb8;
extern const Codebook kAsfHcb9;
extern const Codebook kAsfHcb10;
extern const Codebook kAsfHcb11;
extern const Codebook kAsfHcbSnf;       // Table A.13

// The spectrum codebooks by number (index 0 is unused), and Tables A.14 and
// A.15 by the same number.
extern const std::array<const Codebook*, 12> kAsfSpectrumCodebooks;
extern const std::array<int, 12> kCbDim;
extern const std::array<bool, 12> kUnsignedCb;

// A.2: A-SPX.
extern const Codebook kAspxHcbEnvLevel15F0;
extern const Codebook kAspxHcbEnvLevel15Df;
extern const Codebook kAspxHcbEnvLevel15Dt;
extern const Codebook kAspxHcbEnvBalance15F0;
extern const Codebook kAspxHcbEnvBalance15Df;
extern const Codebook kAspxHcbEnvBalance15Dt;
extern const Codebook kAspxHcbEnvLevel30F0;
extern const Codebook kAspxHcbEnvLevel30Df;
extern const Codebook kAspxHcbEnvLevel30Dt;
extern const Codebook kAspxHcbEnvBalance30F0;
extern const Codebook kAspxHcbEnvBalance30Df;
extern const Codebook kAspxHcbEnvBalance30Dt;
extern const Codebook kAspxHcbNoiseLevelF0;
extern const Codebook kAspxHcbNoiseLevelDf;
extern const Codebook kAspxHcbNoiseLevelDt;
extern const Codebook kAspxHcbNoiseBalanceF0;
extern const Codebook kAspxHcbNoiseBalanceDf;
extern const Codebook kAspxHcbNoiseBalanceDt;

// A.3: A-CPL.
extern const Codebook kAcplHcbAlphaCoarseF0;
extern const Codebook kAcplHcbAlphaFineF0;
extern const Codebook kAcplHcbAlphaCoarseDf;
extern const Codebook kAcplHcbAlphaFineDf;
extern const Codebook kAcplHcbAlphaCoarseDt;
extern const Codebook kAcplHcbAlphaFineDt;
extern const Codebook kAcplHcbBetaCoarseF0;
extern const Codebook kAcplHcbBetaFineF0;
extern const Codebook kAcplHcbBetaCoarseDf;
extern const Codebook kAcplHcbBetaFineDf;
extern const Codebook kAcplHcbBetaCoarseDt;
extern const Codebook kAcplHcbBetaFineDt;
extern const Codebook kAcplHcbBeta3CoarseF0;
extern const Codebook kAcplHcbBeta3FineF0;
extern const Codebook kAcplHcbBeta3CoarseDf;
extern const Codebook kAcplHcbBeta3FineDf;
extern const Codebook kAcplHcbBeta3CoarseDt;
extern const Codebook kAcplHcbBeta3FineDt;
extern const Codebook kAcplHcbGammaCoarseF0;
extern const Codebook kAcplHcbGammaFineF0;
extern const Codebook kAcplHcbGammaCoarseDf;
extern const Codebook kAcplHcbGammaFineDf;
extern const Codebook kAcplHcbGammaCoarseDt;
extern const Codebook kAcplHcbGammaFineDt;

// A.4: dialogue enhancement.
extern const Codebook kDeHcbAbs0;
extern const Codebook kDeHcbDiff0;
extern const Codebook kDeHcbAbs1;
extern const Codebook kDeHcbDiff1;

// A.5: DRC.
extern const Codebook kDrcHcb;

// Part 2 A.1.2: A-JCC.
extern const Codebook kAjccHcbDryCoarseF0;
extern const Codebook kAjccHcbDryFineF0;
extern const Codebook kAjccHcbDryCoarseDf;
extern const Codebook kAjccHcbDryFineDf;
extern const Codebook kAjccHcbDryCoarseDt;
extern const Codebook kAjccHcbDryFineDt;
extern const Codebook kAjccHcbWetCoarseF0;
extern const Codebook kAjccHcbWetFineF0;
extern const Codebook kAjccHcbWetCoarseDf;
extern const Codebook kAjccHcbWetFineDf;
extern const Codebook kAjccHcbWetCoarseDt;
extern const Codebook kAjccHcbWetFineDt;

// Part 2 A.1.1: A-JOC.
extern const Codebook kAjocHcbDryCoarseF0;
extern const Codebook kAjocHcbDryFineF0;
extern const Codebook kAjocHcbDryCoarseDf;
extern const Codebook kAjocHcbDryFineDf;
extern const Codebook kAjocHcbDryCoarseDt;
extern const Codebook kAjocHcbDryFineDt;
extern const Codebook kAjocHcbWetCoarseF0;
extern const Codebook kAjocHcbWetFineF0;
extern const Codebook kAjocHcbWetCoarseDf;
extern const Codebook kAjocHcbWetFineDf;
extern const Codebook kAjocHcbWetCoarseDt;
extern const Codebook kAjocHcbWetFineDt;

// Every codebook above, for a test that walks them all.
extern const std::array<const Codebook*, 84> kAllCodebooks;

}  // namespace iclforge::ac4::detail::tables
