#pragma once

#include <array>
#include <span>

// ETSI TS 103 190-2 V1.3.1 Annex A.2.1, the intermediate spatial format's
// rendering matrices. GENERATED by tools/generators/gen_ac4_tables.py from the
// attachment ts_103190_tables_part2.c; do not edit by hand.

namespace iclforge::ac4::detail::tables {

// Part 2 Table 61's stacked ring formats by isf_config, SR3.1.0.0 to
// SR15.9.5.1, and each one's ISF channels.
inline constexpr std::array<int, 6> kIsfChannels = {4, 8, 10, 14, 15, 30};

// The output layouts of Tables A.25 and A.26 in the order kIsfMatrices holds
// them - 2.x, 5.x, 7.x, 9.x, 5.x.2, 5.x.4, 7.x.2, 7.x.4, 9.x.2 and 9.x.4 -
// and each one's loudspeakers.
inline constexpr std::array<int, 10> kIsfOutputs = {2, 5, 7, 9, 7, 9, 9, 11, 11, 13};

// SR<config>_to_<layout>, [isf_config][layout]: kIsfChannels rows, one per ISF
// channel in the order t = [M1..., U1..., L1..., Z] takes them (clause
// 5.10.3.4), of kIsfOutputs coefficients each, in the float the attachment
// declares.
extern const std::array<std::array<std::span<const float>, 10>, 6>
    kIsfMatrices;

}  // namespace iclforge::ac4::detail::tables
